#pragma once
// GENERATED by gen_input_core.py from shared/wavetypes.h -- do not edit.
// Torch-free twins of ForwardInput / BackwardInput: every buffer as a Buf or
// BufList, every scalar copied, the two non-POD extras as raw torch-free handles.
#include "buf.h"
#include "buflist.h"

struct BoundarySession;   // torch-free (boundary/session.cuh); drivers call ->impl() themselves

struct ForwardInputCore {
    BufList models;
    Buf source;
    Buf lap_coes;
    Buf grad_coes;
    int M{};
    int abcn{};
    Buf sources_loc;
    Buf receivers_loc;
    IntSpan source_field_indices;
    IntSpan receiver_field_indices;
    BufList pml_vals;   // Bind from python
    BufList wavefields;   // Bind from python
    BufList forward_workspace;   // Bind from python: per-call scratch, cuda_layout.forward_workspace_nvar
    BufList derived_models;   // Bind from python: cuda_layout.derived_model_nvar model-shaped slots the driver fills (common/derived_models.h)
    Buf last_two;   // Bind from python
    BufList boundary_cpu;   // Bind from python
    BufList boundary_gpu;   // Bind from python
    BufList boundary_staging;   // Bind from python: FP32 one-timestep bands the scaled (int8/fp16) store quantizes from, Layout.staging_shapes
    CStrList boundary_disk_files;   // Bind from python
    BufList checkpoints;   // Bind from python
    Buf checkpoint_steps;
    bool save_all_wavefields{};
    bool use_boundary_saving{};
    bool use_checkpoint = false;
    bool use_recursive_checkpoint = false;
    bool checkpoint_on_cpu = false;
    bool boundary_on_cpu = false;
    bool boundary_on_disk = false;
    bool boundary_disk_async_read = false;
    bool use_pinned_memory = false;
    bool free_surface{};
    int fs_faces = -1;
    IntSpan pad_lo;
    IntSpan pad_hi;
    BufList eq_aux;
    Buf topo_rows;
    bool has_topo = false;
    Buf topo_category;
    bool use_apm = false;
    unsigned int nt{};
    float dt{};
    FloatSpan spacing;
    int transfer_interval = 1;   // Transfer every time step by default
    int boundary_ring_buffers = 1;
    int boundary_tail_steps = 0;
    BoundarySession* boundary_session = nullptr;
    int checkpoint_interval = 1;
    int checkpoint_count = 0;
    int it_begin = 0;
    int it_end = -1;
    Buf record_out;   // (N, nrec, nt)
    Buf u_allt_out;   // (nt, B, nz[, ny], nx) when save_all_wavefields
    int step_phase = 0;
    int cut_face_mask = 0;
};

struct BackwardInputCore {
    Buf u_forward;
    BufList u_boundary;
    Buf u_last_two;
    BufList checkpoints;
    BufList checkpoint_replay;   // Bind from python: cuda_layout.checkpoint_replay_shapes
    Buf checkpoint_steps;
    BufList adjoint_wavefields;   // Bind from python
    BufList forward_wavefields;   // Bind from python
    BufList adjoint_workspace;   // Bind from python
    BufList derived_models;   // Bind from python: cuda_layout.derived_model_nvar (see ForwardInput)
    BufList boundary_cpu;   // Bind from python
    BufList boundary_gpu;   // Bind from python
    BufList boundary_staging;   // Bind from python: see ForwardInput::boundary_staging
    CStrList boundary_disk_files;   // Bind from python
    BufList models;
    Buf adjoint_source;
    Buf forward_source;
    Buf lap_coes;
    Buf grad_coes;
    int M{};
    int abcn{};
    Buf adjoint_sources_loc;
    Buf forward_sources_loc;
    IntSpan source_field_indices;
    IntSpan receiver_field_indices;
    BufList pml_vals;
    BufList eq_aux;
    unsigned int nt{};
    float dt{};
    FloatSpan spacing;
    bool free_surface{};
    int fs_faces = -1;
    IntSpan pad_lo;
    IntSpan pad_hi;
    Buf topo_rows;
    bool has_topo = false;
    Buf topo_category;
    bool use_apm = false;
    bool checkpoint_on_cpu = false;
    bool boundary_on_cpu = false;
    bool boundary_on_disk = false;
    bool boundary_disk_async_read = false;
    bool use_pinned_memory = false;
    int transfer_interval = 1;   // Transfer every time step by default
    int boundary_ring_buffers = 1;
    int boundary_tail_steps = 0;   // see ForwardInput::boundary_tail_steps
    BoundarySession* boundary_session = nullptr;
    int checkpoint_interval = 1;
    int checkpoint_count = 0;
    bool compute_illumination = true;
    int bw_it_begin = -1;   // -1 sentinel => nt
    int bw_it_end = 0;
    int step_phase = 0;
    BufList grads_out;
    BufList illum_out;
    Buf adcig_out;
    Buf grad_split_iii_out;
    int cut_face_mask = 0;
    int bw_begin() const { return bw_it_begin < 0 ? static_cast<int>(nt) : bw_it_begin; }
    bool bw_stepped() const { return bw_begin() < static_cast<int>(nt) || bw_it_end > 0; }
    bool compute_adcig = false;
    int adcig_max_lag = 0;
};


#include <type_traits>
// These cross the C boundary (core/capi.h): plain memory, no std:: members.
static_assert(std::is_standard_layout<ForwardInputCore>::value, "ForwardInputCore crosses the C boundary");
static_assert(std::is_standard_layout<BackwardInputCore>::value, "BackwardInputCore crosses the C boundary");
