// The one translation unit that instantiates this equation's kernel
// templates: the tables behind the order-dispatch macros in kernels.cuh
// (launch/by_order.cuh).
#include "kernels.cuh"

namespace elastic_tti_sg3d {
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_velocity_kernel_fn, elastic_tti_sg3d_velocity_kernel_by_order, elastic_tti_sg3d_velocity_kernel);
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_stress_kernel_fn, elastic_tti_sg3d_stress_kernel_by_order, elastic_tti_sg3d_stress_kernel);
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_velocity_kernel_nopml_fn, elastic_tti_sg3d_velocity_kernel_nopml_by_order, elastic_tti_sg3d_velocity_kernel_nopml);
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_stress_kernel_nopml_fn, elastic_tti_sg3d_stress_kernel_nopml_by_order, elastic_tti_sg3d_stress_kernel_nopml);
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_stress_adjoint_prepare_fn, elastic_tti_sg3d_stress_adjoint_prepare_by_order, elastic_tti_sg3d_stress_adjoint_prepare);
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_stress_adjoint_apply_fn, elastic_tti_sg3d_stress_adjoint_apply_by_order, elastic_tti_sg3d_stress_adjoint_apply);
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_velocity_adjoint_prepare_fn, elastic_tti_sg3d_velocity_adjoint_prepare_by_order, elastic_tti_sg3d_velocity_adjoint_prepare);
SWEEP_BY_ORDER_TABLE(elastic_tti_sg3d_velocity_adjoint_apply_fn, elastic_tti_sg3d_velocity_adjoint_apply_by_order, elastic_tti_sg3d_velocity_adjoint_apply);
SWEEP_BY_ORDER_TABLE(calculate_grad_elastic_tti_sg3d_nobs_fn, calculate_grad_elastic_tti_sg3d_nobs_by_order, calculate_grad_elastic_tti_sg3d_nobs);
} // namespace elastic_tti_sg3d
