#!/usr/bin/env python3
"""Download the prepared 3D Overthrust models from a GitHub Release.

The full-size Overthrust 3D arrays are too large (~460 MB each) to ship inside
the repository. This script fetches the *already-prepared* numpy files from a
GitHub Release attached to the SWEEP repository, so 3D examples can be run
without going through the SEG/EAGE archive download + vites conversion +
smoothing pipeline (see `download_3d_overthrust.py` if you want that).

Default release: https://github.com/DeepWave-KAUST/sweep/releases/tag/data-v1

Usage:
    python download_release_asset.py                # both true_3d.npy and smooth_3d.npy
    python download_release_asset.py --asset true   # only true_3d.npy
    python download_release_asset.py --tag data-v2  # use a different release
"""

from __future__ import annotations

import argparse
import hashlib
import urllib.request
from pathlib import Path


REPO_OWNER = "DeepWave-KAUST"
REPO_NAME  = "sweep"
DEFAULT_TAG = "data-v1"

# Map asset name -> (filename on disk, expected md5 of current preparation).
# md5 values match the npy files generated by `make_smooth_model.py` /
# `convert_3d_overthrust_vites_to_npy.py` at the time the release was cut.
ASSETS: dict[str, tuple[str, str]] = {
    "true":   ("true_3d.npy",   "1bf438d8fd4a9af2600d2c10456df777"),
    "smooth": ("smooth_3d.npy", "3797d1115af0327a9f234214417928c0"),
}


def file_md5(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.md5()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def release_asset_url(tag: str, filename: str) -> str:
    return (
        f"https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/download/"
        f"{tag}/{filename}"
    )


def download(url: str, dest: Path) -> None:
    def report(block_count: int, block_size: int, total_size: int) -> None:
        if total_size <= 0:
            return
        downloaded = min(block_count * block_size, total_size)
        pct = downloaded * 100.0 / total_size
        print(f"\rDownloading {dest.name}: {pct:6.2f}%", end="", flush=True)

    print(f"GET {url}")
    urllib.request.urlretrieve(url, dest, reporthook=report)
    print()


def fetch(asset: str, tag: str, out_dir: Path, force: bool) -> None:
    filename, expected_md5 = ASSETS[asset]
    dest = out_dir / filename
    if dest.exists() and not force:
        actual_md5 = file_md5(dest)
        if actual_md5 == expected_md5:
            print(f"OK   {dest} (md5 match, skipping)")
            return
        print(f"WARN {dest} exists but md5 differs ({actual_md5}); re-downloading")
    download(release_asset_url(tag, filename), dest)
    actual_md5 = file_md5(dest)
    if actual_md5 != expected_md5:
        raise SystemExit(
            f"md5 mismatch after download: {dest} got {actual_md5}, expected {expected_md5}"
        )
    print(f"OK   {dest} ({dest.stat().st_size // (1024 * 1024)} MB)")


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--asset",
        choices=list(ASSETS) + ["all"],
        default="all",
        help="Which prepared model to fetch. Default: all.",
    )
    parser.add_argument("--tag", default=DEFAULT_TAG, help=f"Release tag. Default: {DEFAULT_TAG}.")
    parser.add_argument("--out-dir", type=Path, default=Path(__file__).resolve().parent,
                        help="Destination directory. Default: this script's directory.")
    parser.add_argument("--force", action="store_true", help="Re-download even if the file is already present and correct.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    targets = list(ASSETS) if args.asset == "all" else [args.asset]
    for asset in targets:
        fetch(asset, args.tag, args.out_dir, args.force)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
