"""Generate the torch-free twins of ForwardInput / BackwardInput from
shared/wavetypes.h, so the twin can never drift from the struct Python fills.

Type mapping (the whole design in one table):
  torch::Tensor               -> Buf
  std::vector<torch::Tensor>  -> BufList
  int/bool/float/unsigned     -> same
  std::vector<int>            -> IntSpan   (pad_lo / pad_hi, rank <= 3)
  std::vector<float>          -> FloatSpan (spacing)
  std::vector<std::string>    -> CStrList  (boundary_disk_files)
  std::shared_ptr<BoundarySession> -> BoundarySessionImpl*  (already torch-free)
Anything else is an error, on purpose: a new field type must be a decision.
"""
import re, sys
src = open(sys.argv[1]).read().split("\n")
MAP = {"torch::Tensor": "Buf", "std::vector<torch::Tensor>": "BufList",
       "int": "int", "bool": "bool", "float": "float", "unsigned int": "unsigned int",
       "int64_t": "int64_t", "double": "double",
       "std::vector<int>": "IntSpan", "std::vector<float>": "FloatSpan",
       "std::vector<std::string>": "CStrList",
       "std::shared_ptr<BoundarySession>": "BoundarySession*"}
def block(name):
    s = next(i for i, l in enumerate(src) if l.startswith(f"struct {name}"))
    e = next(i for i in range(s, len(src)) if src[i].startswith("};"))
    return src[s + 1:e]
out = ['#pragma once', '// GENERATED by gen_input_core.py from shared/wavetypes.h -- do not edit.',
       '// Torch-free twins of ForwardInput / BackwardInput: every buffer as a Buf or',
       '// BufList, every scalar copied, the two non-POD extras as raw torch-free handles.',
       '#include "buf.h"', '#include "buflist.h"', '', 'struct BoundarySession;   // torch-free (boundary/session.cuh); drivers call ->impl() themselves', '']
for name in ("ForwardInput", "BackwardInput"):
    out.append(f"struct {name}Core {{")
    for l in block(name):
        m = re.match(r"\s+((?:const\s+)?[A-Za-z_][A-Za-z_0-9:<>, ]*?\*?)\s+([a-z_0-9]+)\s*(=[^;]*)?;\s*(//.*)?$", l)
        if not m:
            if l.strip() and not l.strip().startswith("//"): out.append(f"    // (skipped non-field line: {l.strip()[:60]})")
            continue
        t, n, default, comment = m.group(1).strip(), m.group(2), m.group(3), m.group(4)
        if t not in MAP: raise SystemExit(f"unmapped field type {t!r} for {n} in {name}")
        ct = MAP[t]
        init = "" if ct in ("Buf", "BufList", "IntSpan", "FloatSpan", "CStrList") else (" = nullptr" if ct.endswith("*") else (default or "").replace("=", "= ").strip() and " " + default.strip() or "{}")
        out.append(f"    {ct} {n}{init};" + (f"   {comment}" if comment else ""))
    out.append("};\n")
open(sys.argv[2], "w").write("\n".join(out))

# ---- the adapter: fill a twin from the torch struct, once per call ---------
# Emitted from the same field walk, so the twin and its filler cannot drift.
# The arena owns the Buf arrays the BufLists point into and the int/float
# copies the spans point into; it must outlive the twin (one per call, on the
# stack of the binding lambda, is the intended use).
ad = ['#pragma once', '// GENERATED by gen_input_core.py from shared/wavetypes.h -- do not edit.',
      '// torch::Tensor -> Buf happens here and nowhere else in the drivers.',
      '#include <vector>', '#include <string>', '#include <torch/extension.h>',
      '#include "../../core/input_core.h"', '#include "buf_torch.h"',
      '',
      'struct InputArena {',
      '    std::vector<std::vector<Buf>> lists;      // one backing array per BufList field',
      '    std::vector<std::vector<int>> ints;       // pad_lo / pad_hi copies',
      '    std::vector<std::vector<float>> floats;   // spacing copy',
      '    std::vector<std::vector<const char*>> cstrs;',
      '    BufList list_of(const std::vector<torch::Tensor>& v) {',
      '        lists.emplace_back(); auto& a = lists.back(); a.reserve(v.size());',
      '        for (const auto& t : v) a.push_back(buf_of(t));',
      '        return BufList{a.data(), static_cast<int64_t>(a.size())};',
      '    }',
      '    IntSpan ints_of(const std::vector<int>& v) { ints.push_back(v); return IntSpan{ints.back().data(), (int64_t)v.size()}; }',
      '    FloatSpan floats_of(const std::vector<float>& v) { floats.push_back(v); return FloatSpan{floats.back().data(), (int64_t)v.size()}; }',
      '    CStrList cstrs_of(const std::vector<std::string>& v) {',
      '        cstrs.emplace_back(); auto& a = cstrs.back(); for (const auto& x : v) a.push_back(x.c_str());',
      '        return CStrList{a.data(), (int64_t)a.size()};',
      '    }',
      '};', '',
      '// NOTE: the arena reserves nothing up front, so a push_back on `lists` may',
      '// reallocate the OUTER vector -- that moves the inner vectors\' handles, not',
      '// their heap storage, so BufLists handed out earlier stay valid. Same for',
      '// ints/floats/cstrs. (Documented because it is the one non-obvious lifetime.)', '']
FILL = {"Buf": "buf_of(in.{n})", "BufList": "ar.list_of(in.{n})", "IntSpan": "ar.ints_of(in.{n})",
        "FloatSpan": "ar.floats_of(in.{n})", "CStrList": "ar.cstrs_of(in.{n})",
        "BoundarySession*": "in.{n}.get()"}
for name in ("ForwardInput", "BackwardInput"):
    ad.append(f"inline {name}Core adapt_input(const {name}& in, InputArena& ar)")
    ad.append("{"); ad.append(f"    {name}Core c;")
    for l in block(name):
        m = re.match(r"\s+((?:const\s+)?[A-Za-z_][A-Za-z_0-9:<>, ]*?\*?)\s+([a-z_0-9]+)\s*(=[^;]*)?;", l)
        if not m: continue
        t, n = m.group(1).strip(), m.group(2); ct = MAP[t]
        ad.append("    c." + n + " = " + FILL.get(ct, "in.{n}").format(n=n) + ";")
    ad.append("    return c;"); ad.append("}"); ad.append("")
open(sys.argv[3], "w").write("\n".join(ad))
print(f"  wrote {sys.argv[3]}")
print(f"  wrote {sys.argv[2]}: {sum(1 for l in out if l.startswith('    ') and not l.startswith('    //'))} fields")
