"""Generate the torch-free twins of ForwardInput / BackwardInput from
shared/wavetypes.h, so the twin can never drift from the struct Python fills.

Type mapping (the whole design in one table):
  torch::Tensor               -> Buf
  std::vector<torch::Tensor>  -> BufList
  int/bool/float/unsigned     -> same
  std::vector<int>            -> IntSpan   (pad_lo / pad_hi, rank <= 3)
  std::vector<float>          -> FloatSpan (spacing)
  std::vector<std::string>    -> CStrList  (boundary_disk_files)
  std::shared_ptr<BoundarySession> -> BoundarySessionImpl*  (already torch-free)
Anything else is an error, on purpose: a new field type must be a decision.

Four files come out of one field walk, so none can drift from the others:
  core/input_core.h          the C++ twins (argv[2])
  cuda/common/adapt_inputs.h the torch -> twin filler (argv[3])
  sweep/backend/c/abi.py     the ctypes mirror of everything that crosses the
                             C boundary, plus the Python-side input classes
  cuda/common/layout.cu      sizeof/offsetof of those structs, exported from
                             the core so the ctypes mirror can check itself
The last two are placed relative to argv[2] (<csrc>/core/input_core.h): the
mirror at <sweep>/backend/c/abi.py, the probe beside the other CUDA sources;
argv[4] / argv[5] override them (a test regenerating into a temp dir).

core/dtype.h's ``enum class BoundaryDtype`` is parsed as well: its values are
the FP32/FP16/BF16/INT8 constants of abi.py AND the last entries of the
layout probe, so a core built from a tree with a reordered enum fails the
load-time guard instead of silently mis-tagging every boundary buffer
(sizeof/offsetof alone cannot see a reordering).
"""
import os, re, sys
src = open(sys.argv[1]).read().split("\n")
core_h, adapt_h = sys.argv[2], sys.argv[3]
csrc = os.path.dirname(os.path.dirname(os.path.abspath(core_h)))
abi_py = sys.argv[4] if len(sys.argv) > 4 else os.path.join(os.path.dirname(csrc), "backend", "c", "abi.py")
layout_cu = sys.argv[5] if len(sys.argv) > 5 else os.path.join(csrc, "cuda", "common", "layout.cu")
# capi.h sits next to wavetypes.h's sibling dir, so the ABI version is read
# from the tree being generated FROM even when the outputs go to a temp dir.
capi_h = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[1]))), "core", "capi.h")
dtype_h = os.path.join(os.path.dirname(capi_h), "dtype.h")
for p in (abi_py, layout_cu):   # fail before writing anything, not after the first file
    if not os.path.isdir(os.path.dirname(p)):
        raise SystemExit(f"no directory for {p}: pass explicit paths as argv[4] (abi.py) and argv[5] (layout.cu)")
# Three tensors the drivers only ever read on the HOST (the field index tables
# through .item<int>(), the checkpoint step table through data_ptr<int>() of a
# CPU copy): the adapter makes the host copy once per call and the twin carries
# a host span / host Buf instead of the device descriptor.
HOST_INT_SPAN = {"source_field_indices", "receiver_field_indices"}
HOST_BUF = {"checkpoint_steps"}
MAP = {"torch::Tensor": "Buf", "std::vector<torch::Tensor>": "BufList",
       "int": "int", "bool": "bool", "float": "float", "unsigned int": "unsigned int",
       "int64_t": "int64_t", "double": "double",
       "std::vector<int>": "IntSpan", "std::vector<float>": "FloatSpan",
       "std::vector<std::string>": "CStrList",
       "std::shared_ptr<BoundarySessionHandle>": "BoundarySession*"}
SPANS = ("Buf", "BufList", "IntSpan", "FloatSpan", "CStrList")
FIELD_RE = re.compile(r"\s+((?:const\s+)?[A-Za-z_][A-Za-z_0-9:<>, ]*?\*?)\s+([A-Za-z_0-9]+)\s*(=[^;]*)?;\s*(//.*)?$")
def block(name):
    s = next(i for i, l in enumerate(src) if l.startswith(f"struct {name}"))
    e = next(i for i in range(s, len(src)) if src[i].startswith("};"))
    return src[s + 1:e]
def fields(name):
    """(name, core kind, C++ default literal or None, trailing comment) per field, header order."""
    out = []
    for l in block(name):
        m = FIELD_RE.match(l)
        if not m: continue
        t, n = m.group(1).strip(), m.group(2)
        if t not in MAP: raise SystemExit(f"unmapped field type {t!r} for {n} in {name}")
        out.append((n, "IntSpan" if n in HOST_INT_SPAN else MAP[t], m.group(3), m.group(4)))
    return out
out = ['#pragma once', '// GENERATED by gen_input_core.py from shared/wavetypes.h -- do not edit.',
       '// Torch-free twins of ForwardInput / BackwardInput: every buffer as a Buf or',
       '// BufList, every scalar copied, the two non-POD extras as raw torch-free handles.',
       '#include "buf.h"', '#include "buflist.h"', '', 'struct BoundarySession;   // torch-free (boundary/session.cuh); drivers call ->impl() themselves', '']
for name in ("ForwardInput", "BackwardInput"):
    out.append(f"struct {name}Core {{")
    for l in block(name):
        m = FIELD_RE.match(l)
        if not m:
            if l.strip().startswith(("int bw_begin() const", "bool bw_stepped() const")):
                out.append("    " + l.strip())   # the two segment helpers, field-only, ride along verbatim
            elif l.strip() and not l.strip().startswith("//"): out.append(f"    // (skipped non-field line: {l.strip()[:60]})")
            continue
        t, n, default, comment = m.group(1).strip(), m.group(2), m.group(3), m.group(4)
        if t not in MAP: raise SystemExit(f"unmapped field type {t!r} for {n} in {name}")
        ct = "IntSpan" if n in HOST_INT_SPAN else MAP[t]
        init = "" if ct in SPANS else (" = nullptr" if ct.endswith("*") else (default or "").replace("=", "= ").strip() and " " + default.strip() or "{}")
        out.append(f"    {ct} {n}{init};" + (f"   {comment}" if comment else ""))
    out.append("};\n")
out += ["", "#include <type_traits>", "// These cross the C boundary (core/capi.h): plain memory, no std:: members.",
        "static_assert(std::is_standard_layout<ForwardInputCore>::value, \"ForwardInputCore crosses the C boundary\");",
        "static_assert(std::is_standard_layout<BackwardInputCore>::value, \"BackwardInputCore crosses the C boundary\");", ""]
open(core_h, "w").write("\n".join(out))

# ---- the adapter: fill a twin from the torch struct, once per call ---------
# Emitted from the same field walk, so the twin and its filler cannot drift.
# The arena owns the Buf arrays the BufLists point into and the int/float
# copies the spans point into; it must outlive the twin (one per call, on the
# stack of the binding lambda, is the intended use).
ad = ['#pragma once', '// GENERATED by gen_input_core.py from shared/wavetypes.h -- do not edit.',
      '// torch::Tensor -> Buf happens here and nowhere else in the drivers.',
      '#include <vector>', '#include <string>', '#include <torch/extension.h>',
      '#include "../../core/input_core.h"', '#include "../../core/outputs.h"', '#include "buf_torch.h"',
      '',
      'struct InputArena {',
      '    std::vector<std::vector<Buf>> lists;      // one backing array per BufList field',
      '    std::vector<std::vector<int>> ints;       // pad_lo / pad_hi copies',
      '    std::vector<std::vector<float>> floats;   // spacing copy',
      '    std::vector<std::vector<const char*>> cstrs;',
      '    BufList list_of(const std::vector<torch::Tensor>& v) {',
      '        lists.emplace_back(); auto& a = lists.back(); a.reserve(v.size());',
      '        for (const auto& t : v) a.push_back(buf_of(t));',
      '        return BufList{a.data(), static_cast<int64_t>(a.size())};',
      '    }',
      '    IntSpan ints_of(const std::vector<int>& v) { ints.push_back(v); return IntSpan{ints.back().data(), (int64_t)v.size()}; }',
      '    // The host copies of the three tensors the drivers read on the host',
      '    // (the .to(kCPU) every driver used to make at entry, made once here).',
      '    std::vector<torch::Tensor> held;',
      '    IntSpan host_ints_of(const torch::Tensor& t) {',
      '        if (!t.defined() || t.numel() == 0) return IntSpan{};',
      '        const auto c = t.to(torch::kCPU).to(torch::kInt32).contiguous();',
      '        ints.emplace_back(c.data_ptr<int>(), c.data_ptr<int>() + c.numel());',
      '        return IntSpan{ints.back().data(), (int64_t)c.numel()};',
      '    }',
      '    Buf host_buf_of(const torch::Tensor& t) {',
      '        if (!t.defined()) return Buf{};',
      '        held.push_back(t.to(torch::kCPU).to(torch::kInt32).contiguous());',
      '        return buf_of(held.back());',
      '    }',
      '    FloatSpan floats_of(const std::vector<float>& v) { floats.push_back(v); return FloatSpan{floats.back().data(), (int64_t)v.size()}; }',
      '    CStrList cstrs_of(const std::vector<std::string>& v) {',
      '        cstrs.emplace_back(); auto& a = cstrs.back(); for (const auto& x : v) a.push_back(x.c_str());',
      '        return CStrList{a.data(), (int64_t)a.size()};',
      '    }',
      '};', '',
      '// NOTE: the arena reserves nothing up front, so a push_back on `lists` may',
      '// reallocate the OUTER vector -- that moves the inner vectors\' handles, not',
      '// their heap storage, so BufLists handed out earlier stay valid. Same for',
      '// ints/floats/cstrs. (Documented because it is the one non-obvious lifetime.)', '']
FILL = {"Buf": "buf_of(in.{n})", "BufList": "ar.list_of(in.{n})", "IntSpan": "ar.ints_of(in.{n})",
        "FloatSpan": "ar.floats_of(in.{n})", "CStrList": "ar.cstrs_of(in.{n})",
        "BoundarySession*": "(in.{n} ? static_cast<BoundarySession*>(in.{n}->h) : nullptr)"}
ad += open(__file__.replace("gen_input_core.py", "input_core_torch_side.inc")).read().splitlines()
for name in ("ForwardInput", "BackwardInput"):
    ad.append(f"inline {name}Core adapt_input(const {name}& in, InputArena& ar)")
    ad.append("{"); ad.append(f"    {name}Core c;")
    for n, ct, _, _ in fields(name):
        fill = ("ar.host_ints_of(in.{n})" if n in HOST_INT_SPAN else
                "ar.host_buf_of(in.{n})" if n in HOST_BUF else FILL.get(ct, "in.{n}"))
        ad.append("    c." + n + " = " + fill.format(n=n) + ";")
    ad.append("    return c;"); ad.append("}"); ad.append("")
open(adapt_h, "w").write("\n".join(ad))
print(f"  wrote {adapt_h}")
print(f"  wrote {core_h}: {sum(1 for l in out if l.startswith('    ') and not l.startswith('    //'))} fields")

# ---- the ctypes mirror + the layout probe --------------------------------
# The hand-written core structs (buf.h, buflist.h, outputs.h) are mirrored from
# this table, not parsed: those headers are mostly inline methods.  Drift is
# caught anyway -- layout.cu takes offsetof() of every name here, so a renamed
# or removed field fails the core build, and a field added on the C side moves
# sizeof(), which the probe reports and the ctypes mirror does not match.
CTYPE = {"int": "c_int32", "unsigned int": "c_uint32", "int64_t": "c_int64", "bool": "c_bool",
         "float": "c_float", "double": "c_double", "BoundarySession*": "c_void_p",
         "Buf": "Buf", "BufList": "BufList", "IntSpan": "IntSpan", "FloatSpan": "FloatSpan", "CStrList": "CStrList"}
FIXED = [   # (struct, [(field, ctypes type)]) in core header order; the probe order too
    ("Buf", [("data_", "c_void_p"), ("sizes_", "c_int64 * BUF_MAX_DIMS"), ("strides_", "c_int64 * BUF_MAX_DIMS"),
             ("numel_", "c_int64"), ("ndim_", "c_int32"), ("elem_size_", "c_int32"), ("dtype_", "c_int32"),
             ("defined_", "c_bool"), ("is_cuda_", "c_bool"), ("device_", "c_int32")]),
    ("BufList", [("p", "POINTER(Buf)"), ("n", "c_int64")]),
    ("IntSpan", [("p", "POINTER(c_int32)"), ("n", "c_int64")]),
    ("FloatSpan", [("p", "POINTER(c_float)"), ("n", "c_int64")]),
    ("CStrList", [("p", "POINTER(c_char_p)"), ("n", "c_int64")]),
    ("GradList", [("items", "Buf * SWEEP_MAX_GRADS"), ("n", "c_int64")]),
    ("ForwardOutputCore", [("wavefield", "Buf"), ("last_two", "Buf"), ("record", "Buf")]),
    ("RTMOutputCore", [("source_illumination", "Buf"), ("receiver_illumination", "Buf"), ("adcig", "Buf")]),
    ("BackwardOutputCore", [("grads", "GradList"), ("source_illumination", "Buf"), ("receiver_illumination", "Buf"), ("adcig", "Buf")]),
]
def py_default(ct, lit):
    """The Python default of a twin field: what the C++ default literal (or
    value-initialisation, when there is none) means on the Python side."""
    if ct == "Buf" or ct.endswith("*"): return None
    if ct in SPANS: return []
    v = (lit or "=").lstrip("=").strip()
    if v == "": return {"bool": False, "float": 0.0, "double": 0.0}.get(ct, 0)
    if v in ("true", "false"): return v == "true"
    if ct in ("float", "double"): return float(v.rstrip("fF"))
    return int(v)
generated = [(f"{name}Core", [(n, CTYPE[ct]) for n, ct, _, _ in fields(name)]) for name in ("ForwardInput", "BackwardInput")]
abi_version = re.search(r"^#define\s+SWEEP_CORE_ABI_VERSION\s+(\d+)", open(capi_h).read(), re.M)
if not abi_version: raise SystemExit(f"SWEEP_CORE_ABI_VERSION not found in {capi_h}")

def enum_values(header, name):
    """[(enumerator, value)] of ``enum class <name>`` in header order; implicit
    values count up from the previous one the way C++ does."""
    m = re.search(r"enum\s+class\s+" + name + r"\b[^{]*\{([^}]*)\}", open(header).read())
    if not m: raise SystemExit(f"enum class {name} not found in {header}")
    out, nxt = [], 0
    for item in m.group(1).split(","):
        item = re.sub(r"//.*", "", item).strip()
        if not item: continue
        mm = re.match(r"^([A-Za-z_]\w*)\s*(?:=\s*(-?\d+))?$", item)
        if not mm: raise SystemExit(f"cannot parse {name} enumerator {item!r} in {header}: `NAME` or `NAME = <int>` only")
        nxt = int(mm.group(2)) if mm.group(2) is not None else nxt
        out.append((mm.group(1), nxt)); nxt += 1
    return out
DTYPE_ENUM = enum_values(dtype_h, "BoundaryDtype")
DTYPE_TAGS = ("FP32", "FP16", "BF16", "INT8")   # the shim's tag names (its width table is keyed on them)
if [n for n, _ in DTYPE_ENUM] != list(DTYPE_TAGS):
    raise SystemExit(f"BoundaryDtype in {dtype_h} is {[n for n, _ in DTYPE_ENUM]}, the shim expects {list(DTYPE_TAGS)}: "
                     "changing the enum is a decision -- update DTYPE_TAGS here and sweep/backend/c/adapt.py's tag table together")
ENUMS = {"BoundaryDtype": DTYPE_ENUM}
# sizeof / offsetof of every struct, then the enumerator values: the enum entries
# go LAST so the struct part of the probe keeps its indices.
probe = [(s, f) for s, fl in FIXED + generated for f in [None] + [n for n, _ in fl]]
probe += [(e, n) for e, vals in ENUMS.items() for n, _ in vals]

py = ['"""GENERATED by gen_input_core.py -- do not edit.',
      '',
      'ctypes mirrors of everything that crosses the core\'s C boundary (csrc/core/',
      '{buf,buflist,outputs,input_core}.h), field for field in header order, so the',
      'pure-Python shim can fill a ForwardInputCore and hand its pointer to',
      'sweep_call() with no compiled adapter.  The layout is NOT trusted: the core',
      'exports sizeof/offsetof of every struct here plus the BoundaryDtype',
      'enumerator values (sweep_layout_probe, in LAYOUT_PROBE order) and the shim',
      'compares them against ctypes_layout() at load, so a header edit without a',
      'regeneration -- or a reordered enum -- is caught before a call.',
      '',
      'ForwardInput / BackwardInput are the plain-attribute stand-ins for the',
      'pybind classes of the same names (sweep/propagator/_c.py fills them); the',
      'shim packs them into the ctypes structs per call.',
      '"""',
      'import ctypes',
      'from ctypes import POINTER, Structure, c_bool, c_char_p, c_double, c_float, c_int32, c_int64, c_uint32, c_void_p',
      '',
      f'ABI_VERSION = {abi_version.group(1)}   # SWEEP_CORE_ABI_VERSION, csrc/core/capi.h',
      'BUF_MAX_DIMS = 8         # core/buf.h',
      'SWEEP_MAX_GRADS = 32     # core/outputs.h',
      '# BoundaryDtype (core/dtype.h, parsed): the tag in Buf.dtype_',
      ", ".join(n for n, _ in DTYPE_ENUM) + " = " + ", ".join(str(v) for _, v in DTYPE_ENUM),
      '# What the (enum, enumerator) entries of LAYOUT_PROBE answer.',
      'ENUMS = {' + ", ".join('"%s": {%s}' % (e, ", ".join('"%s": %s' % (n, n) for n, _ in vals)) for e, vals in ENUMS.items()) + '}',
      '# Tensors the drivers read on the host: the shim hands a host copy, not the',
      '# device descriptor (the adapter did the same).',
      'HOST_INT_SPAN = {' + ', '.join(f'"{x}"' for x in sorted(HOST_INT_SPAN)) + '}',
      'HOST_BUF = {' + ', '.join(f'"{x}"' for x in sorted(HOST_BUF)) + '}',
      '']
for s, fl in FIXED + generated:
    py += ["", "", f"class {s}(Structure):", "    _fields_ = ["]
    py += [f'        ("{n}", {t}),' for n, t in fl]
    py += ["    ]"]
py += ["", "", "STRUCTS = {" + ", ".join(f'"{s}": {s}' for s, _ in FIXED + generated) + "}", "",
       "# (name, core kind, Python default) per twin field, header order: the shim's",
       "# packing table and the input classes' attribute list.",
       "FIELDS = {"]
for name in ("ForwardInput", "BackwardInput"):
    py.append(f'    "{name}Core": [')
    py += [f'        ("{n}", "{ct}", {py_default(ct, lit)!r}),' for n, ct, lit, _ in fields(name)]
    py.append("    ],")
py += ["}", "",
       "# What sweep_layout_probe(i) answers, pair by pair: (struct, None) is its",
       "# sizeof, (struct, field) that field's offsetof, and, after every struct,",
       "# (enum, enumerator) that enumerator's value -- sizeof/offsetof cannot see a",
       "# reordered BoundaryDtype, which would mis-tag every boundary buffer.",
       "# cuda/common/layout.cu is generated from the same table.",
       "LAYOUT_PROBE = ["]
py += [f'    ("{s}", ' + (f'"{f}"' if f else "None") + '),' for s, f in probe]
py += ["]", "", "",
       "def ctypes_layout():",
       '    """The mirror\'s own answer to LAYOUT_PROBE, to compare with the core\'s."""',
       "    out = []",
       "    for s, f in LAYOUT_PROBE:",
       "        if s in ENUMS: out.append(ENUMS[s][f])",
       "        elif f is None: out.append(ctypes.sizeof(STRUCTS[s]))",
       "        else: out.append(getattr(STRUCTS[s], f).offset)",
       "    return out",
       "", "",
       "class _Input(object):",
       "    _fields = ()",
       "    _names = frozenset()   # the field names; what __setattr__ admits",
       "",
       "    def __init__(self):",
       "        for name, _, default in self._fields:",
       "            setattr(self, name, list(default) if isinstance(default, list) else default)",
       "",
       "    def __setattr__(self, name, value):",
       "        # A typo'd field would otherwise be accepted and silently ignored by",
       "        # the shim (the pybind class raised).  Underscore names pass: private",
       "        # bookkeeping a caller hangs on the object is not a field.",
       "        if name not in self._names and not name.startswith(\"_\"):",
       "            raise AttributeError(\"%s has no field %r\" % (type(self).__name__, name))",
       "        object.__setattr__(self, name, value)",
       "",
       "    def __repr__(self):",
       "        # Non-default fields only.  Anything with a .shape is a set tensor and",
       "        # is shown as its shape -- never compared with ==, which a CUDA tensor",
       "        # against a [] default raises on (and whose own repr would drown the",
       "        # rest); lists of buffers as a count.",
       "        parts = []",
       "        for name, kind, default in self._fields:",
       "            v = getattr(self, name)",
       "            shape = getattr(v, \"shape\", None)",
       "            if shape is not None:",
       "                s = \"Tensor<%s>\" % (tuple(shape),)",
       "            elif kind == \"Buf\":",
       "                if v is None: continue",
       "                s = \"<%s>\" % type(v).__name__",
       "            elif kind == \"BufList\":",
       "                if not v: continue",
       "                s = \"[%d bufs]\" % len(v)",
       "            else:",
       "                if v is default or v == default: continue",
       "                s = repr(v)",
       "            parts.append(\"%s=%s\" % (name, s))",
       "        return \"%s(%s)\" % (type(self).__name__, \", \".join(parts))",
       ""]
for name in ("ForwardInput", "BackwardInput"):
    py += ["", f"class {name}(_Input):", f'    _fields = FIELDS["{name}Core"]',
           f'    _names = frozenset(name for name, _, _ in FIELDS["{name}Core"])', ""]
open(abi_py, "w").write("\n".join(py))
print(f"  wrote {abi_py}: {len(probe)} probe entries")

# NOTE: the header comment below still spells the mirror's pre-split path
# (sweep/_core_abi.py; it is sweep/backend/c/abi.py now).  layout.cu is a csrc
# file, and every csrc byte feeds the local core's source stamp
# (backend/c/jit.py _source_stamp), so rewording it alone would rebuild every
# cached local core; update it with the next edit that changes csrc anyway.
cu = ['// GENERATED by gen_input_core.py -- do not edit.',
      '// cuda/common/layout.cu -- sizeof / offsetof of every struct that crosses the',
      '// C boundary (core/capi.h), in the order sweep/_core_abi.py LAYOUT_PROBE lists',
      '// them, so the ctypes mirror can check itself against the compiled core at',
      '// load instead of trusting two hand-kept layouts to agree.  A renamed or',
      '// removed field fails to compile here; an added one moves a sizeof.  The',
      '// BoundaryDtype enumerator values come last: a reordered enum would pass',
      '// the sizeof/offsetof entries and mis-tag every boundary buffer.',
      '#include <cstddef>',
      '#include <cstdint>',
      '#include "../../core/capi.h"',
      '#include "../../core/dtype.h"',
      '#include "../../core/buf.h"',
      '#include "../../core/buflist.h"',
      '#include "../../core/outputs.h"',
      '#include "../../core/input_core.h"',
      '',
      'namespace {',
      'const int64_t kLayout[] = {']
def cu_entry(s, f):
    if s in ENUMS: return f"    static_cast<int64_t>({s}::{f}),"
    if f is None: return f"    static_cast<int64_t>(sizeof({s})),"
    return f"    static_cast<int64_t>(offsetof({s}, {f})),"
cu += [cu_entry(s, f) for s, f in probe]
cu += ['};',
       'const int64_t kLayoutCount = static_cast<int64_t>(sizeof(kLayout) / sizeof(kLayout[0]));',
       '}   // namespace',
       '',
       'extern "C" SWEEP_CAPI int64_t sweep_layout_count(void) { return kLayoutCount; }',
       'extern "C" SWEEP_CAPI int64_t sweep_layout_probe(int64_t i) { return (i < 0 || i >= kLayoutCount) ? -1 : kLayout[i]; }',
       '']
open(layout_cu, "w").write("\n".join(cu))
print(f"  wrote {layout_cu}: {len(probe)} entries")
