#pragma once
// GENERATED by gen_input_core.py from shared/wavetypes.h -- do not edit.
// torch::Tensor -> Buf happens here and nowhere else in the drivers.
#include <vector>
#include <string>
#include <torch/extension.h>
#include "../../core/input_core.h"
#include "buf_torch.h"

struct InputArena {
    std::vector<std::vector<Buf>> lists;      // one backing array per BufList field
    std::vector<std::vector<int>> ints;       // pad_lo / pad_hi copies
    std::vector<std::vector<float>> floats;   // spacing copy
    std::vector<std::vector<const char*>> cstrs;
    BufList list_of(const std::vector<torch::Tensor>& v) {
        lists.emplace_back(); auto& a = lists.back(); a.reserve(v.size());
        for (const auto& t : v) a.push_back(buf_of(t));
        return BufList{a.data(), static_cast<int64_t>(a.size())};
    }
    IntSpan ints_of(const std::vector<int>& v) { ints.push_back(v); return IntSpan{ints.back().data(), (int64_t)v.size()}; }
    FloatSpan floats_of(const std::vector<float>& v) { floats.push_back(v); return FloatSpan{floats.back().data(), (int64_t)v.size()}; }
    CStrList cstrs_of(const std::vector<std::string>& v) {
        cstrs.emplace_back(); auto& a = cstrs.back(); for (const auto& x : v) a.push_back(x.c_str());
        return CStrList{a.data(), (int64_t)a.size()};
    }
};

// NOTE: the arena reserves nothing up front, so a push_back on `lists` may
// reallocate the OUTER vector -- that moves the inner vectors' handles, not
// their heap storage, so BufLists handed out earlier stay valid. Same for
// ints/floats/cstrs. (Documented because it is the one non-obvious lifetime.)

inline ForwardInputCore adapt_input(const ForwardInput& in, InputArena& ar)
{
    ForwardInputCore c;
    c.models = ar.list_of(in.models);
    c.source = buf_of(in.source);
    c.lap_coes = buf_of(in.lap_coes);
    c.grad_coes = buf_of(in.grad_coes);
    c.abcn = in.abcn;
    c.sources_loc = buf_of(in.sources_loc);
    c.receivers_loc = buf_of(in.receivers_loc);
    c.source_field_indices = buf_of(in.source_field_indices);
    c.receiver_field_indices = buf_of(in.receiver_field_indices);
    c.pml_vals = ar.list_of(in.pml_vals);
    c.wavefields = ar.list_of(in.wavefields);
    c.forward_workspace = ar.list_of(in.forward_workspace);
    c.derived_models = ar.list_of(in.derived_models);
    c.last_two = buf_of(in.last_two);
    c.boundary_cpu = ar.list_of(in.boundary_cpu);
    c.boundary_gpu = ar.list_of(in.boundary_gpu);
    c.boundary_staging = ar.list_of(in.boundary_staging);
    c.boundary_disk_files = ar.cstrs_of(in.boundary_disk_files);
    c.checkpoints = ar.list_of(in.checkpoints);
    c.checkpoint_steps = buf_of(in.checkpoint_steps);
    c.save_all_wavefields = in.save_all_wavefields;
    c.use_boundary_saving = in.use_boundary_saving;
    c.use_checkpoint = in.use_checkpoint;
    c.use_recursive_checkpoint = in.use_recursive_checkpoint;
    c.checkpoint_on_cpu = in.checkpoint_on_cpu;
    c.boundary_on_cpu = in.boundary_on_cpu;
    c.boundary_on_disk = in.boundary_on_disk;
    c.boundary_disk_async_read = in.boundary_disk_async_read;
    c.use_pinned_memory = in.use_pinned_memory;
    c.free_surface = in.free_surface;
    c.fs_faces = in.fs_faces;
    c.pad_lo = ar.ints_of(in.pad_lo);
    c.pad_hi = ar.ints_of(in.pad_hi);
    c.eq_aux = ar.list_of(in.eq_aux);
    c.topo_rows = buf_of(in.topo_rows);
    c.has_topo = in.has_topo;
    c.topo_category = buf_of(in.topo_category);
    c.use_apm = in.use_apm;
    c.nt = in.nt;
    c.dt = in.dt;
    c.spacing = ar.floats_of(in.spacing);
    c.transfer_interval = in.transfer_interval;
    c.boundary_ring_buffers = in.boundary_ring_buffers;
    c.boundary_tail_steps = in.boundary_tail_steps;
    c.boundary_session = in.boundary_session.get();
    c.checkpoint_interval = in.checkpoint_interval;
    c.checkpoint_count = in.checkpoint_count;
    c.it_begin = in.it_begin;
    c.it_end = in.it_end;
    c.record_out = buf_of(in.record_out);
    c.u_allt_out = buf_of(in.u_allt_out);
    c.step_phase = in.step_phase;
    c.cut_face_mask = in.cut_face_mask;
    return c;
}

inline BackwardInputCore adapt_input(const BackwardInput& in, InputArena& ar)
{
    BackwardInputCore c;
    c.u_forward = buf_of(in.u_forward);
    c.u_boundary = ar.list_of(in.u_boundary);
    c.u_last_two = buf_of(in.u_last_two);
    c.checkpoints = ar.list_of(in.checkpoints);
    c.checkpoint_replay = ar.list_of(in.checkpoint_replay);
    c.checkpoint_steps = buf_of(in.checkpoint_steps);
    c.adjoint_wavefields = ar.list_of(in.adjoint_wavefields);
    c.forward_wavefields = ar.list_of(in.forward_wavefields);
    c.adjoint_workspace = ar.list_of(in.adjoint_workspace);
    c.derived_models = ar.list_of(in.derived_models);
    c.boundary_cpu = ar.list_of(in.boundary_cpu);
    c.boundary_gpu = ar.list_of(in.boundary_gpu);
    c.boundary_staging = ar.list_of(in.boundary_staging);
    c.boundary_disk_files = ar.cstrs_of(in.boundary_disk_files);
    c.models = ar.list_of(in.models);
    c.adjoint_source = buf_of(in.adjoint_source);
    c.forward_source = buf_of(in.forward_source);
    c.lap_coes = buf_of(in.lap_coes);
    c.grad_coes = buf_of(in.grad_coes);
    c.abcn = in.abcn;
    c.adjoint_sources_loc = buf_of(in.adjoint_sources_loc);
    c.forward_sources_loc = buf_of(in.forward_sources_loc);
    c.source_field_indices = buf_of(in.source_field_indices);
    c.receiver_field_indices = buf_of(in.receiver_field_indices);
    c.pml_vals = ar.list_of(in.pml_vals);
    c.eq_aux = ar.list_of(in.eq_aux);
    c.nt = in.nt;
    c.dt = in.dt;
    c.spacing = ar.floats_of(in.spacing);
    c.free_surface = in.free_surface;
    c.fs_faces = in.fs_faces;
    c.pad_lo = ar.ints_of(in.pad_lo);
    c.pad_hi = ar.ints_of(in.pad_hi);
    c.topo_rows = buf_of(in.topo_rows);
    c.has_topo = in.has_topo;
    c.topo_category = buf_of(in.topo_category);
    c.use_apm = in.use_apm;
    c.checkpoint_on_cpu = in.checkpoint_on_cpu;
    c.boundary_on_cpu = in.boundary_on_cpu;
    c.boundary_on_disk = in.boundary_on_disk;
    c.boundary_disk_async_read = in.boundary_disk_async_read;
    c.use_pinned_memory = in.use_pinned_memory;
    c.transfer_interval = in.transfer_interval;
    c.boundary_ring_buffers = in.boundary_ring_buffers;
    c.boundary_tail_steps = in.boundary_tail_steps;
    c.boundary_session = in.boundary_session.get();
    c.checkpoint_interval = in.checkpoint_interval;
    c.checkpoint_count = in.checkpoint_count;
    c.compute_illumination = in.compute_illumination;
    c.bw_it_begin = in.bw_it_begin;
    c.bw_it_end = in.bw_it_end;
    c.step_phase = in.step_phase;
    c.grads_out = ar.list_of(in.grads_out);
    c.illum_out = ar.list_of(in.illum_out);
    c.adcig_out = buf_of(in.adcig_out);
    c.cut_face_mask = in.cut_face_mask;
    c.compute_adcig = in.compute_adcig;
    c.adcig_max_lag = in.adcig_max_lag;
    return c;
}
