#pragma once
// GENERATED by gen_input_core.py from shared/wavetypes.h -- do not edit.
// torch::Tensor -> Buf happens here and nowhere else in the drivers.
#include <vector>
#include <string>
#include <torch/extension.h>
#include "../../core/input_core.h"
#include "../../core/outputs.h"
#include "buf_torch.h"

struct InputArena {
    std::vector<std::vector<Buf>> lists;      // one backing array per BufList field
    std::vector<std::vector<int>> ints;       // pad_lo / pad_hi copies
    std::vector<std::vector<float>> floats;   // spacing copy
    std::vector<std::vector<const char*>> cstrs;
    BufList list_of(const std::vector<torch::Tensor>& v) {
        lists.emplace_back(); auto& a = lists.back(); a.reserve(v.size());
        for (const auto& t : v) a.push_back(buf_of(t));
        return BufList{a.data(), static_cast<int64_t>(a.size())};
    }
    IntSpan ints_of(const std::vector<int>& v) { ints.push_back(v); return IntSpan{ints.back().data(), (int64_t)v.size()}; }
    // The host copies of the three tensors the drivers read on the host
    // (the .to(kCPU) every driver used to make at entry, made once here).
    std::vector<torch::Tensor> held;
    IntSpan host_ints_of(const torch::Tensor& t) {
        if (!t.defined() || t.numel() == 0) return IntSpan{};
        const auto c = t.to(torch::kCPU).to(torch::kInt32).contiguous();
        ints.emplace_back(c.data_ptr<int>(), c.data_ptr<int>() + c.numel());
        return IntSpan{ints.back().data(), (int64_t)c.numel()};
    }
    Buf host_buf_of(const torch::Tensor& t) {
        if (!t.defined()) return Buf{};
        held.push_back(t.to(torch::kCPU).to(torch::kInt32).contiguous());
        return buf_of(held.back());
    }
    FloatSpan floats_of(const std::vector<float>& v) { floats.push_back(v); return FloatSpan{floats.back().data(), (int64_t)v.size()}; }
    CStrList cstrs_of(const std::vector<std::string>& v) {
        cstrs.emplace_back(); auto& a = cstrs.back(); for (const auto& x : v) a.push_back(x.c_str());
        return CStrList{a.data(), (int64_t)a.size()};
    }
};

// NOTE: the arena reserves nothing up front, so a push_back on `lists` may
// reallocate the OUTER vector -- that moves the inner vectors' handles, not
// their heap storage, so BufLists handed out earlier stay valid. Same for
// ints/floats/cstrs. (Documented because it is the one non-obvious lifetime.)

// A driver's output Buf is one of the tensors the propagator bound (the
// skeletons allocate nothing), so the tensor it stands for is the one with the
// same data pointer.  An undefined Buf maps to an undefined tensor (Python
// sees None).  A Buf that matches nothing is a contract break, reported.
inline torch::Tensor tensor_of(const Buf& b, std::initializer_list<const torch::Tensor*> singles,
                               std::initializer_list<const std::vector<torch::Tensor>*> lists,
                               const char* what)
{
    if (!b.defined()) return torch::Tensor();
    for (const torch::Tensor* t : singles)
        if (t->defined() && t->data_ptr() == b.data_ptr()) return *t;
    for (const std::vector<torch::Tensor>* l : lists)
        for (const auto& t : *l)
            if (t.defined() && t.data_ptr() == b.data_ptr()) return t;
    SWEEP_CHECK(false, what, ": the driver handed back a buffer the propagator did not bind");
    return torch::Tensor();
}

inline ForwardOutput to_torch(const ForwardOutputCore& c, const ForwardInput& in)
{
    ForwardOutput out;
    out.wavefield = tensor_of(c.wavefield, {&in.u_allt_out}, {}, "ForwardOutput.wavefield");
    out.last_two = tensor_of(c.last_two, {&in.last_two}, {}, "ForwardOutput.last_two");
    out.record = tensor_of(c.record, {&in.record_out}, {}, "ForwardOutput.record");
    return out;
}

inline BackwardOutput to_torch(const BackwardOutputCore& c, const BackwardInput& in)
{
    BackwardOutput out;
    out.grads.reserve(c.grads.size());
    for (const auto& g : c.grads)
        out.grads.push_back(tensor_of(g, {}, {&in.grads_out}, "BackwardOutput.grads"));
    out.source_illumination = tensor_of(c.source_illumination, {}, {&in.illum_out}, "BackwardOutput.source_illumination");
    out.receiver_illumination = tensor_of(c.receiver_illumination, {}, {&in.illum_out}, "BackwardOutput.receiver_illumination");
    out.adcig = tensor_of(c.adcig, {&in.adcig_out}, {}, "BackwardOutput.adcig");
    return out;
}

inline RTMOutput to_torch(const RTMOutputCore& c, const BackwardInput& in)
{
    RTMOutput out;
    out.source_illumination = tensor_of(c.source_illumination, {}, {&in.illum_out}, "RTMOutput.source_illumination");
    out.receiver_illumination = tensor_of(c.receiver_illumination, {}, {&in.illum_out}, "RTMOutput.receiver_illumination");
    out.adcig = tensor_of(c.adcig, {&in.adcig_out}, {}, "RTMOutput.adcig");
    return out;
}
inline ForwardInputCore adapt_input(const ForwardInput& in, InputArena& ar)
{
    ForwardInputCore c;
    c.models = ar.list_of(in.models);
    c.source = buf_of(in.source);
    c.lap_coes = buf_of(in.lap_coes);
    c.grad_coes = buf_of(in.grad_coes);
    c.M = in.M;
    c.abcn = in.abcn;
    c.sources_loc = buf_of(in.sources_loc);
    c.receivers_loc = buf_of(in.receivers_loc);
    c.source_field_indices = ar.host_ints_of(in.source_field_indices);
    c.receiver_field_indices = ar.host_ints_of(in.receiver_field_indices);
    c.pml_vals = ar.list_of(in.pml_vals);
    c.wavefields = ar.list_of(in.wavefields);
    c.forward_workspace = ar.list_of(in.forward_workspace);
    c.derived_models = ar.list_of(in.derived_models);
    c.last_two = buf_of(in.last_two);
    c.boundary_cpu = ar.list_of(in.boundary_cpu);
    c.boundary_gpu = ar.list_of(in.boundary_gpu);
    c.boundary_staging = ar.list_of(in.boundary_staging);
    c.boundary_disk_files = ar.cstrs_of(in.boundary_disk_files);
    c.checkpoints = ar.list_of(in.checkpoints);
    c.checkpoint_steps = ar.host_buf_of(in.checkpoint_steps);
    c.save_all_wavefields = in.save_all_wavefields;
    c.use_boundary_saving = in.use_boundary_saving;
    c.use_checkpoint = in.use_checkpoint;
    c.use_recursive_checkpoint = in.use_recursive_checkpoint;
    c.checkpoint_on_cpu = in.checkpoint_on_cpu;
    c.boundary_on_cpu = in.boundary_on_cpu;
    c.boundary_on_disk = in.boundary_on_disk;
    c.boundary_disk_async_read = in.boundary_disk_async_read;
    c.use_pinned_memory = in.use_pinned_memory;
    c.free_surface = in.free_surface;
    c.fs_faces = in.fs_faces;
    c.pad_lo = ar.ints_of(in.pad_lo);
    c.pad_hi = ar.ints_of(in.pad_hi);
    c.eq_aux = ar.list_of(in.eq_aux);
    c.topo_rows = buf_of(in.topo_rows);
    c.has_topo = in.has_topo;
    c.topo_category = buf_of(in.topo_category);
    c.use_apm = in.use_apm;
    c.nt = in.nt;
    c.dt = in.dt;
    c.spacing = ar.floats_of(in.spacing);
    c.transfer_interval = in.transfer_interval;
    c.boundary_ring_buffers = in.boundary_ring_buffers;
    c.boundary_tail_steps = in.boundary_tail_steps;
    c.boundary_session = (in.boundary_session ? static_cast<BoundarySession*>(in.boundary_session->h) : nullptr);
    c.checkpoint_interval = in.checkpoint_interval;
    c.checkpoint_count = in.checkpoint_count;
    c.it_begin = in.it_begin;
    c.it_end = in.it_end;
    c.record_out = buf_of(in.record_out);
    c.u_allt_out = buf_of(in.u_allt_out);
    c.step_phase = in.step_phase;
    c.cut_face_mask = in.cut_face_mask;
    return c;
}

inline BackwardInputCore adapt_input(const BackwardInput& in, InputArena& ar)
{
    BackwardInputCore c;
    c.u_forward = buf_of(in.u_forward);
    c.u_boundary = ar.list_of(in.u_boundary);
    c.u_last_two = buf_of(in.u_last_two);
    c.checkpoints = ar.list_of(in.checkpoints);
    c.checkpoint_replay = ar.list_of(in.checkpoint_replay);
    c.checkpoint_steps = ar.host_buf_of(in.checkpoint_steps);
    c.adjoint_wavefields = ar.list_of(in.adjoint_wavefields);
    c.forward_wavefields = ar.list_of(in.forward_wavefields);
    c.adjoint_workspace = ar.list_of(in.adjoint_workspace);
    c.derived_models = ar.list_of(in.derived_models);
    c.boundary_cpu = ar.list_of(in.boundary_cpu);
    c.boundary_gpu = ar.list_of(in.boundary_gpu);
    c.boundary_staging = ar.list_of(in.boundary_staging);
    c.boundary_disk_files = ar.cstrs_of(in.boundary_disk_files);
    c.models = ar.list_of(in.models);
    c.adjoint_source = buf_of(in.adjoint_source);
    c.forward_source = buf_of(in.forward_source);
    c.lap_coes = buf_of(in.lap_coes);
    c.grad_coes = buf_of(in.grad_coes);
    c.M = in.M;
    c.abcn = in.abcn;
    c.adjoint_sources_loc = buf_of(in.adjoint_sources_loc);
    c.forward_sources_loc = buf_of(in.forward_sources_loc);
    c.source_field_indices = ar.host_ints_of(in.source_field_indices);
    c.receiver_field_indices = ar.host_ints_of(in.receiver_field_indices);
    c.pml_vals = ar.list_of(in.pml_vals);
    c.eq_aux = ar.list_of(in.eq_aux);
    c.nt = in.nt;
    c.dt = in.dt;
    c.spacing = ar.floats_of(in.spacing);
    c.free_surface = in.free_surface;
    c.fs_faces = in.fs_faces;
    c.pad_lo = ar.ints_of(in.pad_lo);
    c.pad_hi = ar.ints_of(in.pad_hi);
    c.topo_rows = buf_of(in.topo_rows);
    c.has_topo = in.has_topo;
    c.topo_category = buf_of(in.topo_category);
    c.use_apm = in.use_apm;
    c.checkpoint_on_cpu = in.checkpoint_on_cpu;
    c.boundary_on_cpu = in.boundary_on_cpu;
    c.boundary_on_disk = in.boundary_on_disk;
    c.boundary_disk_async_read = in.boundary_disk_async_read;
    c.use_pinned_memory = in.use_pinned_memory;
    c.transfer_interval = in.transfer_interval;
    c.boundary_ring_buffers = in.boundary_ring_buffers;
    c.boundary_tail_steps = in.boundary_tail_steps;
    c.boundary_session = (in.boundary_session ? static_cast<BoundarySession*>(in.boundary_session->h) : nullptr);
    c.checkpoint_interval = in.checkpoint_interval;
    c.checkpoint_count = in.checkpoint_count;
    c.compute_illumination = in.compute_illumination;
    c.bw_it_begin = in.bw_it_begin;
    c.bw_it_end = in.bw_it_end;
    c.step_phase = in.step_phase;
    c.grads_out = ar.list_of(in.grads_out);
    c.illum_out = ar.list_of(in.illum_out);
    c.adcig_out = buf_of(in.adcig_out);
    c.grad_split_iii_out = buf_of(in.grad_split_iii_out);
    c.cut_face_mask = in.cut_face_mask;
    c.compute_adcig = in.compute_adcig;
    c.adcig_max_lag = in.adcig_max_lag;
    return c;
}
