"""GENERATED by gen_input_core.py -- do not edit.

ctypes mirrors of everything that crosses the core's C boundary (csrc/core/
{buf,buflist,outputs,input_core}.h), field for field in header order, so the
pure-Python shim can fill a ForwardInputCore and hand its pointer to
sweep_call() with no compiled adapter.  The layout is NOT trusted: the core
exports sizeof/offsetof of every struct here plus the BoundaryDtype
enumerator values (sweep_layout_probe, in LAYOUT_PROBE order) and the shim
compares them against ctypes_layout() at load, so a header edit without a
regeneration -- or a reordered enum -- is caught before a call.

ForwardInput / BackwardInput are the plain-attribute stand-ins for the
pybind classes of the same names (sweep/propagator/_c.py fills them); the
shim packs them into the ctypes structs per call.
"""
import ctypes
from ctypes import POINTER, Structure, c_bool, c_char_p, c_double, c_float, c_int32, c_int64, c_uint32, c_void_p

ABI_VERSION = 2   # SWEEP_CORE_ABI_VERSION, csrc/core/capi.h
BUF_MAX_DIMS = 8         # core/buf.h
SWEEP_MAX_GRADS = 32     # core/outputs.h
# BoundaryDtype (core/dtype.h, parsed): the tag in Buf.dtype_
FP32, FP16, BF16, INT8 = 0, 1, 2, 3
# What the (enum, enumerator) entries of LAYOUT_PROBE answer.
ENUMS = {"BoundaryDtype": {"FP32": FP32, "FP16": FP16, "BF16": BF16, "INT8": INT8}}
# Tensors the drivers read on the host: the shim hands a host copy, not the
# device descriptor (the adapter did the same).
HOST_INT_SPAN = {"receiver_field_indices", "source_field_indices"}
HOST_BUF = {"checkpoint_steps"}



class Buf(Structure):
    _fields_ = [
        ("data_", c_void_p),
        ("sizes_", c_int64 * BUF_MAX_DIMS),
        ("strides_", c_int64 * BUF_MAX_DIMS),
        ("numel_", c_int64),
        ("ndim_", c_int32),
        ("elem_size_", c_int32),
        ("dtype_", c_int32),
        ("defined_", c_bool),
        ("is_cuda_", c_bool),
        ("device_", c_int32),
    ]


class BufList(Structure):
    _fields_ = [
        ("p", POINTER(Buf)),
        ("n", c_int64),
    ]


class IntSpan(Structure):
    _fields_ = [
        ("p", POINTER(c_int32)),
        ("n", c_int64),
    ]


class FloatSpan(Structure):
    _fields_ = [
        ("p", POINTER(c_float)),
        ("n", c_int64),
    ]


class CStrList(Structure):
    _fields_ = [
        ("p", POINTER(c_char_p)),
        ("n", c_int64),
    ]


class GradList(Structure):
    _fields_ = [
        ("items", Buf * SWEEP_MAX_GRADS),
        ("n", c_int64),
    ]


class ForwardOutputCore(Structure):
    _fields_ = [
        ("wavefield", Buf),
        ("last_two", Buf),
        ("record", Buf),
    ]


class RTMOutputCore(Structure):
    _fields_ = [
        ("source_illumination", Buf),
        ("receiver_illumination", Buf),
        ("adcig", Buf),
    ]


class BackwardOutputCore(Structure):
    _fields_ = [
        ("grads", GradList),
        ("source_illumination", Buf),
        ("receiver_illumination", Buf),
        ("adcig", Buf),
    ]


class ForwardInputCore(Structure):
    _fields_ = [
        ("models", BufList),
        ("source", Buf),
        ("lap_coes", Buf),
        ("grad_coes", Buf),
        ("M", c_int32),
        ("abcn", c_int32),
        ("sources_loc", Buf),
        ("receivers_loc", Buf),
        ("source_field_indices", IntSpan),
        ("receiver_field_indices", IntSpan),
        ("pml_vals", BufList),
        ("wavefields", BufList),
        ("forward_workspace", BufList),
        ("derived_models", BufList),
        ("last_two", Buf),
        ("boundary_cpu", BufList),
        ("boundary_gpu", BufList),
        ("boundary_staging", BufList),
        ("boundary_disk_files", CStrList),
        ("checkpoints", BufList),
        ("checkpoint_steps", Buf),
        ("save_all_wavefields", c_bool),
        ("use_boundary_saving", c_bool),
        ("use_checkpoint", c_bool),
        ("use_recursive_checkpoint", c_bool),
        ("checkpoint_on_cpu", c_bool),
        ("boundary_on_cpu", c_bool),
        ("boundary_on_disk", c_bool),
        ("boundary_disk_async_read", c_bool),
        ("use_pinned_memory", c_bool),
        ("free_surface", c_bool),
        ("fs_faces", c_int32),
        ("pad_lo", IntSpan),
        ("pad_hi", IntSpan),
        ("eq_aux", BufList),
        ("topo_rows", Buf),
        ("has_topo", c_bool),
        ("topo_category", Buf),
        ("use_apm", c_bool),
        ("nt", c_uint32),
        ("dt", c_float),
        ("spacing", FloatSpan),
        ("transfer_interval", c_int32),
        ("boundary_ring_buffers", c_int32),
        ("boundary_tail_steps", c_int32),
        ("boundary_session", c_void_p),
        ("checkpoint_interval", c_int32),
        ("checkpoint_count", c_int32),
        ("it_begin", c_int32),
        ("it_end", c_int32),
        ("record_out", Buf),
        ("u_allt_out", Buf),
        ("step_phase", c_int32),
        ("cut_face_mask", c_int32),
    ]


class BackwardInputCore(Structure):
    _fields_ = [
        ("u_forward", Buf),
        ("u_boundary", BufList),
        ("u_last_two", Buf),
        ("checkpoints", BufList),
        ("checkpoint_replay", BufList),
        ("checkpoint_steps", Buf),
        ("adjoint_wavefields", BufList),
        ("forward_wavefields", BufList),
        ("adjoint_workspace", BufList),
        ("derived_models", BufList),
        ("boundary_cpu", BufList),
        ("boundary_gpu", BufList),
        ("boundary_staging", BufList),
        ("boundary_disk_files", CStrList),
        ("models", BufList),
        ("adjoint_source", Buf),
        ("forward_source", Buf),
        ("lap_coes", Buf),
        ("grad_coes", Buf),
        ("M", c_int32),
        ("abcn", c_int32),
        ("adjoint_sources_loc", Buf),
        ("forward_sources_loc", Buf),
        ("source_field_indices", IntSpan),
        ("receiver_field_indices", IntSpan),
        ("pml_vals", BufList),
        ("eq_aux", BufList),
        ("nt", c_uint32),
        ("dt", c_float),
        ("spacing", FloatSpan),
        ("free_surface", c_bool),
        ("fs_faces", c_int32),
        ("pad_lo", IntSpan),
        ("pad_hi", IntSpan),
        ("topo_rows", Buf),
        ("has_topo", c_bool),
        ("topo_category", Buf),
        ("use_apm", c_bool),
        ("checkpoint_on_cpu", c_bool),
        ("boundary_on_cpu", c_bool),
        ("boundary_on_disk", c_bool),
        ("boundary_disk_async_read", c_bool),
        ("use_pinned_memory", c_bool),
        ("transfer_interval", c_int32),
        ("boundary_ring_buffers", c_int32),
        ("boundary_tail_steps", c_int32),
        ("boundary_session", c_void_p),
        ("checkpoint_interval", c_int32),
        ("checkpoint_count", c_int32),
        ("compute_illumination", c_bool),
        ("bw_it_begin", c_int32),
        ("bw_it_end", c_int32),
        ("step_phase", c_int32),
        ("grads_out", BufList),
        ("illum_out", BufList),
        ("adcig_out", Buf),
        ("cut_face_mask", c_int32),
        ("compute_adcig", c_bool),
        ("adcig_max_lag", c_int32),
    ]


STRUCTS = {"Buf": Buf, "BufList": BufList, "IntSpan": IntSpan, "FloatSpan": FloatSpan, "CStrList": CStrList, "GradList": GradList, "ForwardOutputCore": ForwardOutputCore, "RTMOutputCore": RTMOutputCore, "BackwardOutputCore": BackwardOutputCore, "ForwardInputCore": ForwardInputCore, "BackwardInputCore": BackwardInputCore}

# (name, core kind, Python default) per twin field, header order: the shim's
# packing table and the input classes' attribute list.
FIELDS = {
    "ForwardInputCore": [
        ("models", "BufList", []),
        ("source", "Buf", None),
        ("lap_coes", "Buf", None),
        ("grad_coes", "Buf", None),
        ("M", "int", 0),
        ("abcn", "int", 0),
        ("sources_loc", "Buf", None),
        ("receivers_loc", "Buf", None),
        ("source_field_indices", "IntSpan", []),
        ("receiver_field_indices", "IntSpan", []),
        ("pml_vals", "BufList", []),
        ("wavefields", "BufList", []),
        ("forward_workspace", "BufList", []),
        ("derived_models", "BufList", []),
        ("last_two", "Buf", None),
        ("boundary_cpu", "BufList", []),
        ("boundary_gpu", "BufList", []),
        ("boundary_staging", "BufList", []),
        ("boundary_disk_files", "CStrList", []),
        ("checkpoints", "BufList", []),
        ("checkpoint_steps", "Buf", None),
        ("save_all_wavefields", "bool", False),
        ("use_boundary_saving", "bool", False),
        ("use_checkpoint", "bool", False),
        ("use_recursive_checkpoint", "bool", False),
        ("checkpoint_on_cpu", "bool", False),
        ("boundary_on_cpu", "bool", False),
        ("boundary_on_disk", "bool", False),
        ("boundary_disk_async_read", "bool", False),
        ("use_pinned_memory", "bool", False),
        ("free_surface", "bool", False),
        ("fs_faces", "int", -1),
        ("pad_lo", "IntSpan", []),
        ("pad_hi", "IntSpan", []),
        ("eq_aux", "BufList", []),
        ("topo_rows", "Buf", None),
        ("has_topo", "bool", False),
        ("topo_category", "Buf", None),
        ("use_apm", "bool", False),
        ("nt", "unsigned int", 0),
        ("dt", "float", 0.0),
        ("spacing", "FloatSpan", []),
        ("transfer_interval", "int", 1),
        ("boundary_ring_buffers", "int", 1),
        ("boundary_tail_steps", "int", 0),
        ("boundary_session", "BoundarySession*", None),
        ("checkpoint_interval", "int", 1),
        ("checkpoint_count", "int", 0),
        ("it_begin", "int", 0),
        ("it_end", "int", -1),
        ("record_out", "Buf", None),
        ("u_allt_out", "Buf", None),
        ("step_phase", "int", 0),
        ("cut_face_mask", "int", 0),
    ],
    "BackwardInputCore": [
        ("u_forward", "Buf", None),
        ("u_boundary", "BufList", []),
        ("u_last_two", "Buf", None),
        ("checkpoints", "BufList", []),
        ("checkpoint_replay", "BufList", []),
        ("checkpoint_steps", "Buf", None),
        ("adjoint_wavefields", "BufList", []),
        ("forward_wavefields", "BufList", []),
        ("adjoint_workspace", "BufList", []),
        ("derived_models", "BufList", []),
        ("boundary_cpu", "BufList", []),
        ("boundary_gpu", "BufList", []),
        ("boundary_staging", "BufList", []),
        ("boundary_disk_files", "CStrList", []),
        ("models", "BufList", []),
        ("adjoint_source", "Buf", None),
        ("forward_source", "Buf", None),
        ("lap_coes", "Buf", None),
        ("grad_coes", "Buf", None),
        ("M", "int", 0),
        ("abcn", "int", 0),
        ("adjoint_sources_loc", "Buf", None),
        ("forward_sources_loc", "Buf", None),
        ("source_field_indices", "IntSpan", []),
        ("receiver_field_indices", "IntSpan", []),
        ("pml_vals", "BufList", []),
        ("eq_aux", "BufList", []),
        ("nt", "unsigned int", 0),
        ("dt", "float", 0.0),
        ("spacing", "FloatSpan", []),
        ("free_surface", "bool", False),
        ("fs_faces", "int", -1),
        ("pad_lo", "IntSpan", []),
        ("pad_hi", "IntSpan", []),
        ("topo_rows", "Buf", None),
        ("has_topo", "bool", False),
        ("topo_category", "Buf", None),
        ("use_apm", "bool", False),
        ("checkpoint_on_cpu", "bool", False),
        ("boundary_on_cpu", "bool", False),
        ("boundary_on_disk", "bool", False),
        ("boundary_disk_async_read", "bool", False),
        ("use_pinned_memory", "bool", False),
        ("transfer_interval", "int", 1),
        ("boundary_ring_buffers", "int", 1),
        ("boundary_tail_steps", "int", 0),
        ("boundary_session", "BoundarySession*", None),
        ("checkpoint_interval", "int", 1),
        ("checkpoint_count", "int", 0),
        ("compute_illumination", "bool", True),
        ("bw_it_begin", "int", -1),
        ("bw_it_end", "int", 0),
        ("step_phase", "int", 0),
        ("grads_out", "BufList", []),
        ("illum_out", "BufList", []),
        ("adcig_out", "Buf", None),
        ("cut_face_mask", "int", 0),
        ("compute_adcig", "bool", False),
        ("adcig_max_lag", "int", 0),
    ],
}

# What sweep_layout_probe(i) answers, pair by pair: (struct, None) is its
# sizeof, (struct, field) that field's offsetof, and, after every struct,
# (enum, enumerator) that enumerator's value -- sizeof/offsetof cannot see a
# reordered BoundaryDtype, which would mis-tag every boundary buffer.
# cuda/common/layout.cu is generated from the same table.
LAYOUT_PROBE = [
    ("Buf", None),
    ("Buf", "data_"),
    ("Buf", "sizes_"),
    ("Buf", "strides_"),
    ("Buf", "numel_"),
    ("Buf", "ndim_"),
    ("Buf", "elem_size_"),
    ("Buf", "dtype_"),
    ("Buf", "defined_"),
    ("Buf", "is_cuda_"),
    ("Buf", "device_"),
    ("BufList", None),
    ("BufList", "p"),
    ("BufList", "n"),
    ("IntSpan", None),
    ("IntSpan", "p"),
    ("IntSpan", "n"),
    ("FloatSpan", None),
    ("FloatSpan", "p"),
    ("FloatSpan", "n"),
    ("CStrList", None),
    ("CStrList", "p"),
    ("CStrList", "n"),
    ("GradList", None),
    ("GradList", "items"),
    ("GradList", "n"),
    ("ForwardOutputCore", None),
    ("ForwardOutputCore", "wavefield"),
    ("ForwardOutputCore", "last_two"),
    ("ForwardOutputCore", "record"),
    ("RTMOutputCore", None),
    ("RTMOutputCore", "source_illumination"),
    ("RTMOutputCore", "receiver_illumination"),
    ("RTMOutputCore", "adcig"),
    ("BackwardOutputCore", None),
    ("BackwardOutputCore", "grads"),
    ("BackwardOutputCore", "source_illumination"),
    ("BackwardOutputCore", "receiver_illumination"),
    ("BackwardOutputCore", "adcig"),
    ("ForwardInputCore", None),
    ("ForwardInputCore", "models"),
    ("ForwardInputCore", "source"),
    ("ForwardInputCore", "lap_coes"),
    ("ForwardInputCore", "grad_coes"),
    ("ForwardInputCore", "M"),
    ("ForwardInputCore", "abcn"),
    ("ForwardInputCore", "sources_loc"),
    ("ForwardInputCore", "receivers_loc"),
    ("ForwardInputCore", "source_field_indices"),
    ("ForwardInputCore", "receiver_field_indices"),
    ("ForwardInputCore", "pml_vals"),
    ("ForwardInputCore", "wavefields"),
    ("ForwardInputCore", "forward_workspace"),
    ("ForwardInputCore", "derived_models"),
    ("ForwardInputCore", "last_two"),
    ("ForwardInputCore", "boundary_cpu"),
    ("ForwardInputCore", "boundary_gpu"),
    ("ForwardInputCore", "boundary_staging"),
    ("ForwardInputCore", "boundary_disk_files"),
    ("ForwardInputCore", "checkpoints"),
    ("ForwardInputCore", "checkpoint_steps"),
    ("ForwardInputCore", "save_all_wavefields"),
    ("ForwardInputCore", "use_boundary_saving"),
    ("ForwardInputCore", "use_checkpoint"),
    ("ForwardInputCore", "use_recursive_checkpoint"),
    ("ForwardInputCore", "checkpoint_on_cpu"),
    ("ForwardInputCore", "boundary_on_cpu"),
    ("ForwardInputCore", "boundary_on_disk"),
    ("ForwardInputCore", "boundary_disk_async_read"),
    ("ForwardInputCore", "use_pinned_memory"),
    ("ForwardInputCore", "free_surface"),
    ("ForwardInputCore", "fs_faces"),
    ("ForwardInputCore", "pad_lo"),
    ("ForwardInputCore", "pad_hi"),
    ("ForwardInputCore", "eq_aux"),
    ("ForwardInputCore", "topo_rows"),
    ("ForwardInputCore", "has_topo"),
    ("ForwardInputCore", "topo_category"),
    ("ForwardInputCore", "use_apm"),
    ("ForwardInputCore", "nt"),
    ("ForwardInputCore", "dt"),
    ("ForwardInputCore", "spacing"),
    ("ForwardInputCore", "transfer_interval"),
    ("ForwardInputCore", "boundary_ring_buffers"),
    ("ForwardInputCore", "boundary_tail_steps"),
    ("ForwardInputCore", "boundary_session"),
    ("ForwardInputCore", "checkpoint_interval"),
    ("ForwardInputCore", "checkpoint_count"),
    ("ForwardInputCore", "it_begin"),
    ("ForwardInputCore", "it_end"),
    ("ForwardInputCore", "record_out"),
    ("ForwardInputCore", "u_allt_out"),
    ("ForwardInputCore", "step_phase"),
    ("ForwardInputCore", "cut_face_mask"),
    ("BackwardInputCore", None),
    ("BackwardInputCore", "u_forward"),
    ("BackwardInputCore", "u_boundary"),
    ("BackwardInputCore", "u_last_two"),
    ("BackwardInputCore", "checkpoints"),
    ("BackwardInputCore", "checkpoint_replay"),
    ("BackwardInputCore", "checkpoint_steps"),
    ("BackwardInputCore", "adjoint_wavefields"),
    ("BackwardInputCore", "forward_wavefields"),
    ("BackwardInputCore", "adjoint_workspace"),
    ("BackwardInputCore", "derived_models"),
    ("BackwardInputCore", "boundary_cpu"),
    ("BackwardInputCore", "boundary_gpu"),
    ("BackwardInputCore", "boundary_staging"),
    ("BackwardInputCore", "boundary_disk_files"),
    ("BackwardInputCore", "models"),
    ("BackwardInputCore", "adjoint_source"),
    ("BackwardInputCore", "forward_source"),
    ("BackwardInputCore", "lap_coes"),
    ("BackwardInputCore", "grad_coes"),
    ("BackwardInputCore", "M"),
    ("BackwardInputCore", "abcn"),
    ("BackwardInputCore", "adjoint_sources_loc"),
    ("BackwardInputCore", "forward_sources_loc"),
    ("BackwardInputCore", "source_field_indices"),
    ("BackwardInputCore", "receiver_field_indices"),
    ("BackwardInputCore", "pml_vals"),
    ("BackwardInputCore", "eq_aux"),
    ("BackwardInputCore", "nt"),
    ("BackwardInputCore", "dt"),
    ("BackwardInputCore", "spacing"),
    ("BackwardInputCore", "free_surface"),
    ("BackwardInputCore", "fs_faces"),
    ("BackwardInputCore", "pad_lo"),
    ("BackwardInputCore", "pad_hi"),
    ("BackwardInputCore", "topo_rows"),
    ("BackwardInputCore", "has_topo"),
    ("BackwardInputCore", "topo_category"),
    ("BackwardInputCore", "use_apm"),
    ("BackwardInputCore", "checkpoint_on_cpu"),
    ("BackwardInputCore", "boundary_on_cpu"),
    ("BackwardInputCore", "boundary_on_disk"),
    ("BackwardInputCore", "boundary_disk_async_read"),
    ("BackwardInputCore", "use_pinned_memory"),
    ("BackwardInputCore", "transfer_interval"),
    ("BackwardInputCore", "boundary_ring_buffers"),
    ("BackwardInputCore", "boundary_tail_steps"),
    ("BackwardInputCore", "boundary_session"),
    ("BackwardInputCore", "checkpoint_interval"),
    ("BackwardInputCore", "checkpoint_count"),
    ("BackwardInputCore", "compute_illumination"),
    ("BackwardInputCore", "bw_it_begin"),
    ("BackwardInputCore", "bw_it_end"),
    ("BackwardInputCore", "step_phase"),
    ("BackwardInputCore", "grads_out"),
    ("BackwardInputCore", "illum_out"),
    ("BackwardInputCore", "adcig_out"),
    ("BackwardInputCore", "cut_face_mask"),
    ("BackwardInputCore", "compute_adcig"),
    ("BackwardInputCore", "adcig_max_lag"),
    ("BoundaryDtype", "FP32"),
    ("BoundaryDtype", "FP16"),
    ("BoundaryDtype", "BF16"),
    ("BoundaryDtype", "INT8"),
]


def ctypes_layout():
    """The mirror's own answer to LAYOUT_PROBE, to compare with the core's."""
    out = []
    for s, f in LAYOUT_PROBE:
        if s in ENUMS: out.append(ENUMS[s][f])
        elif f is None: out.append(ctypes.sizeof(STRUCTS[s]))
        else: out.append(getattr(STRUCTS[s], f).offset)
    return out


class _Input(object):
    _fields = ()
    _names = frozenset()   # the field names; what __setattr__ admits

    def __init__(self):
        for name, _, default in self._fields:
            setattr(self, name, list(default) if isinstance(default, list) else default)

    def __setattr__(self, name, value):
        # A typo'd field would otherwise be accepted and silently ignored by
        # the shim (the pybind class raised).  Underscore names are the shim's
        # per-object cache and pass.
        if name not in self._names and not name.startswith("_"):
            raise AttributeError("%s has no field %r" % (type(self).__name__, name))
        object.__setattr__(self, name, value)

    def __repr__(self):
        # Non-default fields only.  Anything with a .shape is a set tensor and
        # is shown as its shape -- never compared with ==, which a CUDA tensor
        # against a [] default raises on (and whose own repr would drown the
        # rest); lists of buffers as a count.
        parts = []
        for name, kind, default in self._fields:
            v = getattr(self, name)
            shape = getattr(v, "shape", None)
            if shape is not None:
                s = "Tensor<%s>" % (tuple(shape),)
            elif kind == "Buf":
                if v is None: continue
                s = "<%s>" % type(v).__name__
            elif kind == "BufList":
                if not v: continue
                s = "[%d bufs]" % len(v)
            else:
                if v is default or v == default: continue
                s = repr(v)
            parts.append("%s=%s" % (name, s))
        return "%s(%s)" % (type(self).__name__, ", ".join(parts))


class ForwardInput(_Input):
    _fields = FIELDS["ForwardInputCore"]
    _names = frozenset(name for name, _, _ in FIELDS["ForwardInputCore"])


class BackwardInput(_Input):
    _fields = FIELDS["BackwardInputCore"]
    _names = frozenset(name for name, _, _ in FIELDS["BackwardInputCore"])
