from dataclasses import dataclass
from typing import Any
from typing import Literal


@dataclass
class EagerOptions:
    use_compile: bool = ...
    compile_mode: str = ...
    compile_dynamic: bool = ...
    compile_backend: str | None = ...
    compile_fullgraph: bool = ...
    store_last_wavefield: bool = ...


@dataclass
class BoundaryOptions:
    storage: Literal["gpu", "cpu", "disk"] = ...
    transfer_interval: int = ...
    pinned_memory: bool = ...
    disk_dir: str | None = ...
    ring_buffers: int = ...
    disk_async_read: bool = ...


@dataclass
class CkptOptions:
    mode: Literal["chunk", "recursive"] = ...
    chunks: int = ...
    count: int = ...
    storage: Literal["gpu", "cpu"] = ...
    pinned_memory: bool | None = ...


@dataclass
class MemoryOptions:
    strategy: Literal["boundary", "ckpt"] | None = ...
    boundary: BoundaryOptions | None = ...
    ckpt: CkptOptions | None = ...


@dataclass
class CUDAOptions:
    memory: MemoryOptions | None = ...


def options_to_dict(value: Any) -> Any: ...
