from dataclasses import dataclass
from typing import Any
from typing import Literal


@dataclass
class EagerDefaults:
    use_compile: bool = ...
    compile_mode: str = ...
    compile_dynamic: bool = ...
    compile_backend: str | None = ...
    compile_fullgraph: bool = ...
    store_last_wavefield: bool = ...


@dataclass
class BoundaryDefaults:
    enabled: bool = ...
    storage: Literal["gpu", "cpu", "disk"] = ...
    transfer_interval: int | None = ...
    pinned_memory: bool | None = ...
    disk_dir: str | None = ...
    ring_buffers: int | None = ...
    disk_async_read: bool = ...
    gpu_transfer_interval: int = ...
    gpu_pinned_memory: bool = ...
    gpu_ring_buffers: int = ...
    cpu_transfer_interval: int = ...
    cpu_ring_buffers: int = ...
    cpu_pinned_memory: bool = ...
    disk_transfer_interval: int = ...
    disk_async_transfer_interval_2d: int = ...
    disk_async_transfer_interval_3d: int = ...
    disk_ring_buffers_2d: int = ...
    disk_ring_buffers_3d: int = ...
    disk_async_ring_buffers: int = ...


@dataclass
class CkptDefaults:
    mode: Literal["chunk", "recursive"] = ...
    chunks: int = ...
    count: int = ...
    storage: Literal["gpu", "cpu"] = ...
    pinned_memory: bool | None = ...
    cpu_pinned_memory: bool = ...


@dataclass
class PropagatorDefaults:
    abcn: int = ...
    free_surface: bool = ...
    dh: float = ...
    dt: float = ...
    dev: str | None = ...
    use_ckpt: bool | None = ...
    nt: int = ...
    batch_size: int = ...
    allow_growth: bool = ...
    full_mode: str = ...


EAGER_DEFAULTS: EagerDefaults
BOUNDARY_DEFAULTS: BoundaryDefaults
CKPT_DEFAULTS: CkptDefaults
PROP_DEFAULTS: PropagatorDefaults


@dataclass
class EagerOptions:
    use_compile: bool = ...
    compile_mode: str = ...
    compile_dynamic: bool = ...
    compile_backend: str | None = ...
    compile_fullgraph: bool = ...
    store_last_wavefield: bool = ...


@dataclass
class BoundaryOptions:
    storage: Literal["gpu", "cpu", "disk"] = ...
    transfer_interval: int | None = ...
    pinned_memory: bool | None = ...
    disk_dir: str | None = ...
    ring_buffers: int | None = ...
    disk_async_read: bool = ...
    storage_dtype: Literal["fp32", "fp16", "bf16", "int8"] = ...
    tail_steps: int | None = ...


@dataclass
class CkptOptions:
    mode: Literal["chunk", "recursive"] = ...
    chunks: int = ...
    count: int = ...
    storage: Literal["gpu", "cpu"] = ...
    pinned_memory: bool | None = ...


@dataclass
class MemoryOptions:
    strategy: Literal["full", "boundary", "ckpt"] | None = ...
    boundary: BoundaryOptions | None = ...
    ckpt: CkptOptions | None = ...


@dataclass
class CUDAOptions:
    memory: MemoryOptions | None = ...


def options_to_dict(value: Any) -> Any: ...


def resolve_memory_strategy(
    impl: str,
    memory: MemoryOptions | dict[str, Any] | None = ...,
    use_ckpt: bool | None = ...,
    boundary_saving_config: dict[str, Any] | None = ...,
) -> Literal["full", "boundary", "ckpt"]: ...
