// bindings/module.cpp -- the torch shim.  GENERATED by the 4c apply script
// from the C API's entry table (core/capi.h); the core is reached only through
// that C API: adapt the torch struct, call, map the outputs back by pointer
// identity.  Same Python surface as before (names, tuples, docstrings).  CUDA
// tensors only: a host tensor is refused before the core sees it.
#include <torch/extension.h>
#include <cstdint>
#include <memory>
#include <stdexcept>
#include <string>

#include "shared/wavetypes.h"
#include "core/capi.h"
#include "core/input_core.h"
#include "core/outputs.h"
#include "cuda/common/adapt_inputs.h"
#include "bindings_utils.h"

// Some CUDA 12.x / libstdc++ header combinations emit a reference to this
// glibc 2.32 symbol even when building on older glibc hosts. Defining the weak
// fallback as 0 keeps libstdc++ on the conservative multi-threaded path.
extern "C" {
__attribute__((weak)) char __libc_single_threaded = 0;
}

namespace {

constexpr int ID_acoustic2d_forward = 0;
constexpr int ID_acoustic2d_backward = 1;
constexpr int ID_acoustic2d_backward_bs = 2;
constexpr int ID_acoustic2d_backward_ckpt = 3;
constexpr int ID_acoustic2d_backward_recursive_ckpt = 4;
constexpr int ID_acoustic3d_forward = 5;
constexpr int ID_acoustic3d_backward = 6;
constexpr int ID_acoustic3d_backward_bs = 7;
constexpr int ID_acoustic3d_backward_ckpt = 8;
constexpr int ID_acoustic3d_backward_recursive_ckpt = 9;
constexpr int ID_acoustic_lsrtm2d_forward = 10;
constexpr int ID_acoustic_lsrtm2d_backward = 11;
constexpr int ID_acoustic_lsrtm2d_backward_bs = 12;
constexpr int ID_acoustic_lsrtm2d_backward_ckpt = 13;
constexpr int ID_acoustic_lsrtm2d_backward_recursive_ckpt = 14;
constexpr int ID_acoustic_lsrtm3d_forward = 15;
constexpr int ID_acoustic_lsrtm3d_backward = 16;
constexpr int ID_acoustic_lsrtm3d_backward_bs = 17;
constexpr int ID_acoustic_lsrtm3d_backward_ckpt = 18;
constexpr int ID_acoustic_lsrtm3d_backward_recursive_ckpt = 19;
constexpr int ID_acoustic_vrz2d_forward = 20;
constexpr int ID_acoustic_vrz2d_backward = 21;
constexpr int ID_acoustic_vrz2d_backward_bs = 22;
constexpr int ID_acoustic_vrz2d_backward_ckpt = 23;
constexpr int ID_acoustic_vrz2d_backward_recursive_ckpt = 24;
constexpr int ID_acoustic_vrz3d_forward = 25;
constexpr int ID_acoustic_vrz3d_backward = 26;
constexpr int ID_acoustic_vrz3d_backward_bs = 27;
constexpr int ID_acoustic_vrz3d_backward_ckpt = 28;
constexpr int ID_acoustic_vrz3d_backward_recursive_ckpt = 29;
constexpr int ID_acoustic_vti_1st_2d_forward = 30;
constexpr int ID_acoustic_vti_1st_2d_backward = 31;
constexpr int ID_acoustic_vti_1st_2d_backward_bs = 32;
constexpr int ID_acoustic_vti_1st_2d_backward_ckpt = 33;
constexpr int ID_acoustic_vti_1st_2d_backward_recursive_ckpt = 34;
constexpr int ID_acoustic_vti_1st_3d_forward = 35;
constexpr int ID_acoustic_vti_1st_3d_backward = 36;
constexpr int ID_acoustic_vti_1st_3d_backward_bs = 37;
constexpr int ID_acoustic_vti_1st_3d_backward_ckpt = 38;
constexpr int ID_acoustic_vti_1st_3d_backward_recursive_ckpt = 39;
constexpr int ID_das2d_forward = 40;
constexpr int ID_das2d_backward = 41;
constexpr int ID_das2d_backward_bs = 42;
constexpr int ID_das2d_backward_ckpt = 43;
constexpr int ID_das2d_backward_recursive_ckpt = 44;
constexpr int ID_das3d_forward = 45;
constexpr int ID_das3d_backward = 46;
constexpr int ID_das3d_backward_bs = 47;
constexpr int ID_das3d_backward_ckpt = 48;
constexpr int ID_das3d_backward_recursive_ckpt = 49;
constexpr int ID_das_mu2d_forward = 50;
constexpr int ID_das_mu2d_backward = 51;
constexpr int ID_das_mu2d_backward_bs = 52;
constexpr int ID_das_mu2d_backward_ckpt = 53;
constexpr int ID_das_mu2d_backward_recursive_ckpt = 54;
constexpr int ID_das_mu3d_forward = 55;
constexpr int ID_das_mu3d_backward = 56;
constexpr int ID_das_mu3d_backward_bs = 57;
constexpr int ID_das_mu3d_backward_ckpt = 58;
constexpr int ID_das_mu3d_backward_recursive_ckpt = 59;
constexpr int ID_elastic2d_forward = 60;
constexpr int ID_elastic2d_backward = 61;
constexpr int ID_elastic2d_backward_bs = 62;
constexpr int ID_elastic2d_backward_ckpt = 63;
constexpr int ID_elastic2d_backward_recursive_ckpt = 64;
constexpr int ID_elastic2d_apm_forward = 65;
constexpr int ID_elastic3d_forward = 66;
constexpr int ID_elastic3d_backward_bs = 67;
constexpr int ID_elastic3d_backward_ckpt = 68;
constexpr int ID_elastic3d_backward_recursive_ckpt = 69;
constexpr int ID_elastic3d_backward = 70;
constexpr int ID_elastic3d_apm_forward = 71;
constexpr int ID_elastic_tti_2nd2d_forward = 72;
constexpr int ID_elastic_tti_2nd2d_backward = 73;
constexpr int ID_elastic_tti_2nd2d_backward_bs = 74;
constexpr int ID_elastic_tti_2nd2d_backward_ckpt = 75;
constexpr int ID_elastic_tti_sg2d_forward = 76;
constexpr int ID_elastic_tti_sg2d_backward = 77;
constexpr int ID_elastic_tti_sg2d_backward_bs = 78;
constexpr int ID_elastic_tti_sg2d_backward_ckpt = 79;
constexpr int ID_elastic_tti_sg3d_forward = 80;
constexpr int ID_elastic_tti_sg3d_backward = 81;
constexpr int ID_elastic_tti_sg3d_backward_bs = 82;
constexpr int ID_elastic_tti_sg3d_backward_ckpt = 83;
constexpr int ID_elastic_vr2d_forward = 84;
constexpr int ID_elastic_vr2d_backward = 85;
constexpr int ID_elastic_vr2d_backward_bs = 86;
constexpr int ID_elastic_vr2d_backward_ckpt = 87;
constexpr int ID_elastic_vr2d_backward_recursive_ckpt = 88;
constexpr int ID_visco_acoustic2d_forward = 89;
constexpr int ID_visco_acoustic2d_backward = 90;
constexpr int ID_visco_acoustic2d_backward_bs = 91;
constexpr int ID_visco_acoustic2d_backward_ckpt = 92;
constexpr int ID_visco_acoustic2d_backward_recursive_ckpt = 93;

[[noreturn]] void raise_core(const char* err) { throw std::runtime_error(err); }

// The core dereferences every model on the device: a host tensor there is a
// crash (or silent garbage), not a message.  Same words as the ctypes layer
// (_launch_stream in backend/c/entries.py).
void require_cuda_models(int entry, const std::vector<torch::Tensor>& models)
{
    if (!models.empty() && !models[0].is_cuda())
        throw std::runtime_error(std::string(sweep_entry_name(entry)) + ": models[0] is a " +
                                 models[0].device().str() + " tensor; the CUDA core expected "
                                 "a CUDA tensor (move the models to the device first)");
}

ForwardOutput call_forward(int entry, const ForwardInput& in)
{
    require_cuda_models(entry, in.models);
    InputArena arena;
    const ForwardInputCore c = adapt_input(in, arena);
    ForwardOutputCore out;
    char err[2048];
    if (sweep_call(entry, &c, &out, err, sizeof err)) raise_core(err);
    return to_torch(out, in);
}

BackwardOutput call_backward(int entry, const BackwardInput& in)
{
    require_cuda_models(entry, in.models);
    InputArena arena;
    const BackwardInputCore c = adapt_input(in, arena);
    BackwardOutputCore out;
    char err[2048];
    if (sweep_call(entry, &c, &out, err, sizeof err)) raise_core(err);
    return to_torch(out, in);
}

RTMOutput call_rtm(int entry, const BackwardInput& in)
{
    require_cuda_models(entry, in.models);
    InputArena arena;
    const BackwardInputCore c = adapt_input(in, arena);
    RTMOutputCore out;
    char err[2048];
    if (sweep_call(entry, &c, &out, err, sizeof err)) raise_core(err);
    return to_torch(out, in);
}

// A stepped runner: the torch input and the arena its core twin's spans point
// into live here for the handle's life; every run() maps the outputs back.
struct ShimForwardRunner final : IForwardRunner {
    ForwardInput in_;
    InputArena arena_;
    ForwardInputCore core_;
    void* h_ = nullptr;
    ShimForwardRunner(int entry, const ForwardInput& in) : in_(in), core_(adapt_input(in_, arena_))
    {
        require_cuda_models(entry, in_.models);
        char err[2048];
        if (sweep_forward_runner_create(entry, &core_, &h_, err, sizeof err)) raise_core(err);
    }
    ~ShimForwardRunner() override { if (h_) sweep_forward_runner_destroy(h_); }
    ForwardOutput run(int it_begin, int it_end, int step_phase) override
    {
        ForwardOutputCore out;
        char err[2048];
        if (sweep_forward_runner_run(h_, it_begin, it_end, step_phase, &out, err, sizeof err)) raise_core(err);
        return to_torch(out, in_);
    }
    int device_index() const override { return sweep_forward_runner_device_index(h_); }
};

struct ShimBackwardRunner final : IBackwardRunner {
    BackwardInput in_;
    InputArena arena_;
    BackwardInputCore core_;
    void* h_ = nullptr;
    ShimBackwardRunner(int entry, const BackwardInput& in) : in_(in), core_(adapt_input(in_, arena_))
    {
        require_cuda_models(entry, in_.models);
        char err[2048];
        if (sweep_backward_runner_create(entry, &core_, &h_, err, sizeof err)) raise_core(err);
    }
    ~ShimBackwardRunner() override { if (h_) sweep_backward_runner_destroy(h_); }
    BackwardOutput run(int bw_it_begin, int bw_it_end, int step_phase) override
    {
        BackwardOutputCore out;
        char err[2048];
        if (sweep_backward_runner_run(h_, bw_it_begin, bw_it_end, step_phase, &out, err, sizeof err)) raise_core(err);
        return to_torch(out, in_);
    }
    int device_index() const override { return sweep_backward_runner_device_index(h_); }
};

}  // namespace

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    TORCH_CHECK(sweep_core_abi_version() == SWEEP_CORE_ABI_VERSION,
                "sweep core ABI ", sweep_core_abi_version(), " != the shim's ", SWEEP_CORE_ABI_VERSION);
    for (int i = 0; i < SWEEP_ENTRY_COUNT; ++i)   // the ids above are the table's: pin it
        TORCH_CHECK(sweep_entry_name(i) != nullptr, "sweep core entry table is short at ", i);

    // Persistent boundary-staging session.  Python owns it and hands the SAME
    // object to every per-step call of a DD time loop, so the copy stream and
    // the ring events survive between steps and a transfer can actually overlap
    // the next step's compute.  A handle on the core's session (core/capi.h).
    py::class_<BoundarySessionHandle, std::shared_ptr<BoundarySessionHandle>>(m, "BoundarySession")
        .def(py::init<>())
        .def("finish", &BoundarySessionHandle::finish,
             "Let every outstanding copy land and close the current phase.")
        .def_property_readonly("used", &BoundarySessionHandle::used,
             "False when no call site ever bound this session.");

    m.def("acoustic2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic2d_forward, in); }));
    m.def("acoustic2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic2d_backward, in); }), "Acoustic backward (CUDA)");
    m.def("acoustic2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic2d_backward_bs, in); }), "Acoustic backward with boundary saving (CUDA)");
    m.def("acoustic2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic2d_backward_ckpt, in); }), "Acoustic backward with checkpointing (CUDA)");
    m.def("acoustic2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic2d_backward_recursive_ckpt, in); }), "Acoustic backward with recursive checkpointing (CUDA)");
    m.def("acoustic3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic3d_forward, in); }), "Acoustic forward 3D (CUDA)");
    m.def("acoustic3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic3d_backward, in); }), "Acoustic backward 3D (CUDA)");
    m.def("acoustic3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic3d_backward_bs, in); }), "Acoustic backward with boundary saving 3D (CUDA)");
    m.def("acoustic3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic3d_backward_ckpt, in); }), "Acoustic backward with checkpointing 3D (CUDA)");
    m.def("acoustic3d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic3d_backward_recursive_ckpt, in); }), "Acoustic backward with recursive checkpointing 3D (CUDA)");
    m.def("acoustic_lsrtm2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic_lsrtm2d_forward, in); }), "Acoustic LSRTM forward 2D (CUDA)");
    m.def("acoustic_lsrtm2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm2d_backward, in); }), "Acoustic LSRTM backward 2D (CUDA)");
    m.def("acoustic_lsrtm2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm2d_backward_bs, in); }), "Acoustic LSRTM backward with boundary saving 2D (CUDA)");
    m.def("acoustic_lsrtm2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm2d_backward_ckpt, in); }), "Acoustic LSRTM backward with checkpointing 2D (CUDA)");
    m.def("acoustic_lsrtm2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm2d_backward_recursive_ckpt, in); }), "Acoustic LSRTM backward with recursive checkpointing 2D (CUDA)");
    m.def("acoustic_lsrtm3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic_lsrtm3d_forward, in); }), "Acoustic LSRTM forward 3D (CUDA)");
    m.def("acoustic_lsrtm3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm3d_backward, in); }), "Acoustic LSRTM backward 3D (CUDA)");
    m.def("acoustic_lsrtm3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm3d_backward_bs, in); }), "Acoustic LSRTM backward with boundary saving 3D (CUDA)");
    m.def("acoustic_lsrtm3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm3d_backward_ckpt, in); }), "Acoustic LSRTM backward with checkpointing 3D (CUDA)");
    m.def("acoustic_lsrtm3d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_lsrtm3d_backward_recursive_ckpt, in); }), "Acoustic LSRTM backward with recursive checkpointing 3D (CUDA)");
    m.def("acoustic_vrz2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic_vrz2d_forward, in); }), "Acoustic VRZ forward 2D (CUDA)");
    m.def("acoustic_vrz2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz2d_backward, in); }), "Acoustic VRZ backward 2D (CUDA)");
    m.def("acoustic_vrz2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz2d_backward_bs, in); }), "Acoustic VRZ backward with boundary saving 2D (CUDA)");
    m.def("acoustic_vrz2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz2d_backward_ckpt, in); }), "Acoustic VRZ backward with checkpointing 2D (CUDA)");
    m.def("acoustic_vrz2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz2d_backward_recursive_ckpt, in); }), "Acoustic VRZ backward with recursive checkpointing 2D (CUDA)");
    m.def("acoustic_vrz3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic_vrz3d_forward, in); }), "Acoustic VRZ forward 3D (CUDA)");
    m.def("acoustic_vrz3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz3d_backward, in); }), "Acoustic VRZ backward 3D (CUDA)");
    m.def("acoustic_vrz3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz3d_backward_bs, in); }), "Acoustic VRZ backward with boundary saving 3D (CUDA)");
    m.def("acoustic_vrz3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz3d_backward_ckpt, in); }), "Acoustic VRZ backward with checkpointing 3D (CUDA)");
    m.def("acoustic_vrz3d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vrz3d_backward_recursive_ckpt, in); }), "Acoustic VRZ backward with recursive checkpointing 3D (CUDA)");
    m.def("acoustic_vti_1st_2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic_vti_1st_2d_forward, in); }), "AcousticVTI1st (Duveneck 2008) forward 2D (CUDA only, slim)");
    m.def("acoustic_vti_1st_2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_2d_backward, in); }), "AcousticVTI1st backward 2D (NotImplemented stub — raises TORCH_CHECK)");
    m.def("acoustic_vti_1st_2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_2d_backward_bs, in); }), "AcousticVTI1st backward 2D boundary-saving (NotImplemented stub)");
    m.def("acoustic_vti_1st_2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_2d_backward_ckpt, in); }), "AcousticVTI1st backward 2D checkpoint (NotImplemented stub)");
    m.def("acoustic_vti_1st_2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_2d_backward_recursive_ckpt, in); }), "AcousticVTI1st backward 2D recursive ckpt (NotImplemented stub)");
    m.def("acoustic_vti_1st_3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_acoustic_vti_1st_3d_forward, in); }), "AcousticVTI1st (Duveneck 2008) forward 3D (CUDA only)");
    m.def("acoustic_vti_1st_3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_3d_backward, in); }), "AcousticVTI1st backward 3D (full mode, CUDA only)");
    m.def("acoustic_vti_1st_3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_3d_backward_bs, in); }), "AcousticVTI1st backward 3D boundary-saving (CUDA only)");
    m.def("acoustic_vti_1st_3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_3d_backward_ckpt, in); }), "AcousticVTI1st backward 3D chunk-checkpoint (CUDA only)");
    m.def("acoustic_vti_1st_3d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_acoustic_vti_1st_3d_backward_recursive_ckpt, in); }), "AcousticVTI1st backward 3D recursive ckpt (NotImplemented stub)");
    m.def("das2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_das2d_forward, in); }), "DAS forward 2D (CUDA)");
    m.def("das2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das2d_backward, in); }), "DAS backward 2D (CUDA)");
    m.def("das2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das2d_backward_bs, in); }), "DAS backward with boundary saving 2D (CUDA)");
    m.def("das2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das2d_backward_ckpt, in); }), "DAS backward with checkpointing 2D (CUDA)");
    m.def("das2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das2d_backward_recursive_ckpt, in); }), "DAS backward with recursive checkpointing 2D (CUDA)");
    m.def("das3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_das3d_forward, in); }), "DAS forward 3D (CUDA)");
    m.def("das3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das3d_backward, in); }), "DAS backward 3D (CUDA)");
    m.def("das3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das3d_backward_bs, in); }), "DAS backward with boundary saving 3D (CUDA)");
    m.def("das3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das3d_backward_ckpt, in); }), "DAS backward with checkpointing 3D (CUDA)");
    m.def("das3d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das3d_backward_recursive_ckpt, in); }), "DAS backward with recursive checkpointing 3D (CUDA)");
    m.def("das_mu2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_das_mu2d_forward, in); }), "DAS Mu forward 2D (CUDA)");
    m.def("das_mu2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu2d_backward, in); }), "DAS Mu backward 2D (CUDA)");
    m.def("das_mu2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu2d_backward_bs, in); }), "DAS Mu backward with boundary saving 2D (CUDA)");
    m.def("das_mu2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu2d_backward_ckpt, in); }), "DAS Mu backward with checkpointing 2D (CUDA)");
    m.def("das_mu2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu2d_backward_recursive_ckpt, in); }), "DAS Mu backward with recursive checkpointing 2D (CUDA)");
    m.def("das_mu3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_das_mu3d_forward, in); }), "DAS Mu forward 3D (CUDA)");
    m.def("das_mu3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu3d_backward, in); }), "DAS Mu backward 3D (CUDA)");
    m.def("das_mu3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu3d_backward_bs, in); }), "DAS Mu backward with boundary saving 3D (CUDA)");
    m.def("das_mu3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu3d_backward_ckpt, in); }), "DAS Mu backward with checkpointing 3D (CUDA)");
    m.def("das_mu3d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_das_mu3d_backward_recursive_ckpt, in); }), "DAS Mu backward with recursive checkpointing 3D (CUDA)");
    m.def("elastic2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic2d_forward, in); }), "Elastic forward 2D (CUDA)");
    m.def("elastic2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic2d_backward, in); }), "Elastic backward 2D (CUDA)");
    m.def("elastic2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic2d_backward_bs, in); }), "Elastic backward with boundary saving 2D (CUDA)");
    m.def("elastic2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic2d_backward_ckpt, in); }), "Elastic backward with checkpointing 2D (CUDA)");
    m.def("elastic2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic2d_backward_recursive_ckpt, in); }), "Elastic backward with recursive checkpointing 2D (CUDA)");
    m.def("elastic2d_apm_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic2d_apm_forward, in); }), "Elastic APM forward 2D (CUDA only)");
    m.def("elastic3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic3d_forward, in); }), "Elastic forward 3D (CUDA)");
    m.def("elastic3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic3d_backward_bs, in); }), "Elastic backward with boundary saving 3D (CUDA)");
    m.def("elastic3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic3d_backward_ckpt, in); }), "Elastic backward with checkpointing 3D (CUDA)");
    m.def("elastic3d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic3d_backward_recursive_ckpt, in); }), "Elastic backward with recursive checkpointing 3D (CUDA)");
    m.def("elastic3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic3d_backward, in); }), "Elastic backward 3D (CUDA)");
    m.def("elastic3d_apm_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic3d_apm_forward, in); }), "Elastic APM forward 3D (CUDA only)");
    m.def("elastic_tti_2nd2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic_tti_2nd2d_forward, in); }), "Displacement-based elastic TTI (Oh et al. 2020) forward 2D (CUDA only)");
    m.def("elastic_tti_2nd2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_2nd2d_backward, in); }), "Displacement-based elastic TTI backward 2D full mode (CUDA only)");
    m.def("elastic_tti_2nd2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_2nd2d_backward_bs, in); }), "Displacement-based elastic TTI backward 2D boundary-saving mode (CUDA only)");
    m.def("elastic_tti_2nd2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_2nd2d_backward_ckpt, in); }), "Displacement-based elastic TTI backward 2D checkpoint mode (CUDA only)");
    m.def("elastic_tti_sg2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic_tti_sg2d_forward, in); }), "Elastic TTI staggered-grid forward 2D (CUDA)");
    m.def("elastic_tti_sg2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_sg2d_backward, in); }), "Elastic TTI staggered-grid backward 2D full mode (CUDA)");
    m.def("elastic_tti_sg2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_sg2d_backward_bs, in); }), "Elastic TTI staggered-grid backward 2D boundary-saving mode (CUDA)");
    m.def("elastic_tti_sg2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_sg2d_backward_ckpt, in); }), "Elastic TTI staggered-grid backward 2D checkpoint mode (CUDA)");
    m.def("elastic_tti_sg3d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic_tti_sg3d_forward, in); }), "Elastic TTI staggered-grid forward 3D (CUDA only)");
    m.def("elastic_tti_sg3d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_sg3d_backward, in); }), "Elastic TTI staggered-grid backward 3D full mode (CUDA only)");
    m.def("elastic_tti_sg3d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_sg3d_backward_bs, in); }), "Elastic TTI staggered-grid backward 3D boundary-saving mode (CUDA only)");
    m.def("elastic_tti_sg3d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_tti_sg3d_backward_ckpt, in); }), "Elastic TTI staggered-grid backward 3D checkpoint mode (CUDA only)");
    m.def("elastic_vr2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_elastic_vr2d_forward, in); }), "Elastic vector-reflectivity forward 2D (CUDA only)");
    m.def("elastic_vr2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_vr2d_backward, in); }), "Elastic vector-reflectivity backward 2D full (CUDA only)");
    m.def("elastic_vr2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_vr2d_backward_bs, in); }), "Elastic vector-reflectivity backward 2D boundary-saving (CUDA only)");
    m.def("elastic_vr2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_vr2d_backward_ckpt, in); }), "Elastic vector-reflectivity backward 2D checkpoint (CUDA only)");
    m.def("elastic_vr2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_elastic_vr2d_backward_recursive_ckpt, in); }), "Elastic vector-reflectivity backward 2D recursive checkpoint (CUDA only)");
    m.def("visco_acoustic2d_forward", wrap_forward([](const ForwardInput& in) { return call_forward(ID_visco_acoustic2d_forward, in); }), "Visco-acoustic forward 2D (CUDA only)");
    m.def("visco_acoustic2d_backward", wrap_backward([](const BackwardInput& in) { return call_backward(ID_visco_acoustic2d_backward, in); }), "Visco-acoustic backward 2D full mode (CUDA only)");
    m.def("visco_acoustic2d_backward_bs", wrap_backward([](const BackwardInput& in) { return call_backward(ID_visco_acoustic2d_backward_bs, in); }), "Visco-acoustic backward 2D boundary-saving (unsupported: raises)");
    m.def("visco_acoustic2d_backward_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_visco_acoustic2d_backward_ckpt, in); }), "Visco-acoustic backward 2D with checkpointing (CUDA only)");
    m.def("visco_acoustic2d_backward_recursive_ckpt", wrap_backward([](const BackwardInput& in) { return call_backward(ID_visco_acoustic2d_backward_recursive_ckpt, in); }), "Visco-acoustic backward 2D with recursive checkpointing (CUDA only)");

    m.def("visco_acoustic2d_fft_workspace_bytes",
          [](int64_t B, int64_t nz, int64_t nx) { return sweep_visco_fft_workspace_bytes(B, nz, nx); },
          "Work-area bytes of the visco-acoustic spectral step's cuFFT plan for a (B, 1, nz, nx) grid on the current device.");

    py::class_<ForwardInput>(m, "ForwardInput")
        .def(py::init<>())
        .def_readwrite("models", &ForwardInput::models)
        .def_readwrite("source", &ForwardInput::source)
        .def_readwrite("lap_coes", &ForwardInput::lap_coes)
        .def_readwrite("grad_coes", &ForwardInput::grad_coes)
        .def_readwrite("M", &ForwardInput::M)
        .def_readwrite("abcn", &ForwardInput::abcn)
        .def_readwrite("sources_loc", &ForwardInput::sources_loc)
        .def_readwrite("receivers_loc", &ForwardInput::receivers_loc)
        .def_readwrite("source_field_indices", &ForwardInput::source_field_indices)
        .def_readwrite("receiver_field_indices", &ForwardInput::receiver_field_indices)
        .def_readwrite("pml_vals", &ForwardInput::pml_vals)
        .def_readwrite("eq_aux", &ForwardInput::eq_aux)
        .def_readwrite("last_two", &ForwardInput::last_two)
        .def_readwrite("save_all_wavefields", &ForwardInput::save_all_wavefields)
        .def_readwrite("use_boundary_saving", &ForwardInput::use_boundary_saving)
        .def_readwrite("use_checkpoint", &ForwardInput::use_checkpoint)
        .def_readwrite("use_recursive_checkpoint", &ForwardInput::use_recursive_checkpoint)
        .def_readwrite("checkpoint_on_cpu", &ForwardInput::checkpoint_on_cpu)
        .def_readwrite("boundary_on_cpu", &ForwardInput::boundary_on_cpu)
        .def_readwrite("boundary_on_disk", &ForwardInput::boundary_on_disk)
        .def_readwrite("boundary_disk_async_read", &ForwardInput::boundary_disk_async_read)
        .def_readwrite("use_pinned_memory", &ForwardInput::use_pinned_memory)
        .def_readwrite("free_surface", &ForwardInput::free_surface)
        .def_readwrite("fs_faces", &ForwardInput::fs_faces)
        .def_readwrite("pad_lo", &ForwardInput::pad_lo)
        .def_readwrite("pad_hi", &ForwardInput::pad_hi)
        .def_readwrite("topo_rows", &ForwardInput::topo_rows)
        .def_readwrite("has_topo", &ForwardInput::has_topo)
        .def_readwrite("topo_category", &ForwardInput::topo_category)
        .def_readwrite("use_apm", &ForwardInput::use_apm)
        .def_readwrite("nt", &ForwardInput::nt)
        .def_readwrite("dt", &ForwardInput::dt)
        .def_readwrite("spacing", &ForwardInput::spacing)
        .def_readwrite("transfer_interval", &ForwardInput::transfer_interval)
        .def_readwrite("boundary_ring_buffers", &ForwardInput::boundary_ring_buffers)
        .def_readwrite("boundary_session", &ForwardInput::boundary_session)
        .def_readwrite("boundary_tail_steps", &ForwardInput::boundary_tail_steps)
        .def_readwrite("checkpoint_interval", &ForwardInput::checkpoint_interval)
        .def_readwrite("checkpoint_count", &ForwardInput::checkpoint_count)
        .def_readwrite("it_begin", &ForwardInput::it_begin)
        .def_readwrite("it_end", &ForwardInput::it_end)
        .def_readwrite("step_phase", &ForwardInput::step_phase)
        .def_readwrite("cut_face_mask", &ForwardInput::cut_face_mask)
        .def_readwrite("record_out", &ForwardInput::record_out)
        .def_readwrite("u_allt_out", &ForwardInput::u_allt_out)
        .def_readwrite("wavefields", &ForwardInput::wavefields)
        .def_readwrite("forward_workspace", &ForwardInput::forward_workspace)
        .def_readwrite("derived_models", &ForwardInput::derived_models)
        .def_readwrite("boundary_cpu", &ForwardInput::boundary_cpu)
        .def_readwrite("boundary_gpu", &ForwardInput::boundary_gpu)
        .def_readwrite("boundary_staging", &ForwardInput::boundary_staging)
        .def_readwrite("boundary_disk_files", &ForwardInput::boundary_disk_files)
        .def_readwrite("checkpoints", &ForwardInput::checkpoints)
        .def_readwrite("checkpoint_steps", &ForwardInput::checkpoint_steps);

    py::class_<BackwardInput>(m, "BackwardInput")
        .def(py::init<>())
        .def_readwrite("u_forward", &BackwardInput::u_forward)
        .def_readwrite("u_boundary", &BackwardInput::u_boundary)
        .def_readwrite("u_last_two", &BackwardInput::u_last_two)
        .def_readwrite("checkpoints", &BackwardInput::checkpoints)
        .def_readwrite("checkpoint_replay", &BackwardInput::checkpoint_replay)
        .def_readwrite("models", &BackwardInput::models)
        .def_readwrite("adjoint_source", &BackwardInput::adjoint_source)
        .def_readwrite("forward_source", &BackwardInput::forward_source)
        .def_readwrite("lap_coes", &BackwardInput::lap_coes)
        .def_readwrite("grad_coes", &BackwardInput::grad_coes)
        .def_readwrite("M", &BackwardInput::M)
        .def_readwrite("abcn", &BackwardInput::abcn)
        .def_readwrite("adjoint_sources_loc", &BackwardInput::adjoint_sources_loc)
        .def_readwrite("forward_sources_loc", &BackwardInput::forward_sources_loc)
        .def_readwrite("source_field_indices", &BackwardInput::source_field_indices)
        .def_readwrite("receiver_field_indices", &BackwardInput::receiver_field_indices)
        .def_readwrite("pml_vals", &BackwardInput::pml_vals)
        .def_readwrite("eq_aux", &BackwardInput::eq_aux)
        .def_readwrite("nt", &BackwardInput::nt)
        .def_readwrite("dt", &BackwardInput::dt)
        .def_readwrite("spacing", &BackwardInput::spacing)
        .def_readwrite("free_surface", &BackwardInput::free_surface)
        .def_readwrite("fs_faces", &BackwardInput::fs_faces)
        .def_readwrite("pad_lo", &BackwardInput::pad_lo)
        .def_readwrite("pad_hi", &BackwardInput::pad_hi)
        .def_readwrite("topo_rows", &BackwardInput::topo_rows)
        .def_readwrite("has_topo", &BackwardInput::has_topo)
        .def_readwrite("topo_category", &BackwardInput::topo_category)
        .def_readwrite("use_apm", &BackwardInput::use_apm)
        .def_readwrite("checkpoint_on_cpu", &BackwardInput::checkpoint_on_cpu)
        .def_readwrite("boundary_on_cpu", &BackwardInput::boundary_on_cpu)
        .def_readwrite("boundary_on_disk", &BackwardInput::boundary_on_disk)
        .def_readwrite("boundary_disk_async_read", &BackwardInput::boundary_disk_async_read)
        .def_readwrite("use_pinned_memory", &BackwardInput::use_pinned_memory)
        .def_readwrite("transfer_interval", &BackwardInput::transfer_interval)
        .def_readwrite("boundary_ring_buffers", &BackwardInput::boundary_ring_buffers)
        .def_readwrite("boundary_session", &BackwardInput::boundary_session)
        .def_readwrite("boundary_tail_steps", &BackwardInput::boundary_tail_steps)
        .def_readwrite("checkpoint_interval", &BackwardInput::checkpoint_interval)
        .def_readwrite("checkpoint_count", &BackwardInput::checkpoint_count)
        .def_readwrite("bw_it_begin", &BackwardInput::bw_it_begin)
        .def_readwrite("bw_it_end", &BackwardInput::bw_it_end)
        .def_readwrite("step_phase", &BackwardInput::step_phase)
        .def_readwrite("grads_out", &BackwardInput::grads_out)
        .def_readwrite("illum_out", &BackwardInput::illum_out)
        .def_readwrite("adcig_out", &BackwardInput::adcig_out)
        .def_readwrite("cut_face_mask", &BackwardInput::cut_face_mask)
        .def_readwrite("forward_wavefields", &BackwardInput::forward_wavefields)
        .def_readwrite("adjoint_wavefields", &BackwardInput::adjoint_wavefields)
        .def_readwrite("adjoint_workspace", &BackwardInput::adjoint_workspace)
        .def_readwrite("derived_models", &BackwardInput::derived_models)
        .def_readwrite("boundary_cpu", &BackwardInput::boundary_cpu)
        .def_readwrite("boundary_gpu", &BackwardInput::boundary_gpu)
        .def_readwrite("boundary_staging", &BackwardInput::boundary_staging)
        .def_readwrite("boundary_disk_files", &BackwardInput::boundary_disk_files)
        .def_readwrite("checkpoint_steps", &BackwardInput::checkpoint_steps)
        .def_readwrite("compute_illumination", &BackwardInput::compute_illumination)
        .def_readwrite("compute_adcig", &BackwardInput::compute_adcig)
        .def_readwrite("adcig_max_lag", &BackwardInput::adcig_max_lag);


    // ---- Persistent stepped runners (CUDA only) ----
    // Construct once from a populated input struct (prologue: validation,
    // binding, runtime construction), then run(it_begin, it_end, step_phase)
    // per segment.  Same output tuple layout as the plain entries.
    py::class_<IForwardRunner, ForwardRunnerPtr>(m, "ForwardRunner")
        .def("run", [](IForwardRunner& r, int it_begin, int it_end, int step_phase) {
            CoreStreamScope stream(torch_stream_for_device(r.device_index()));
            auto out = r.run(it_begin, it_end, step_phase);
            return std::make_tuple(out.wavefield, out.last_two, out.record);
        });
    py::class_<IBackwardRunner, BackwardRunnerPtr>(m, "BackwardRunner")
        .def("run", [](IBackwardRunner& r, int bw_it_begin, int bw_it_end, int step_phase) {
            CoreStreamScope stream(torch_stream_for_device(r.device_index()));
            auto out = r.run(bw_it_begin, bw_it_end, step_phase);
            return std::make_tuple(out.checkpoints, out.grads,
                                   out.source_illumination,
                                   out.receiver_illumination,
                                   out.adcig);
        });
    // Test probe: the stream the core launches on for this input (what the
    // core's current_stream() answers inside an entry), as an integer handle.
    m.def("_core_stream_for", with_stream_forward([](const ForwardInput&) {
        return reinterpret_cast<std::intptr_t>(sweep_get_stream());
    }));
    m.def("acoustic2d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_acoustic2d_forward, in); }));
    m.def("acoustic2d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_acoustic2d_backward_bs, in); }));
    m.def("acoustic3d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_acoustic3d_forward, in); }));
    m.def("acoustic3d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_acoustic3d_backward_bs, in); }));
    m.def("acoustic_vrz2d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_acoustic_vrz2d_forward, in); }));
    m.def("acoustic_vrz2d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_acoustic_vrz2d_backward_bs, in); }));
    m.def("acoustic_vrz3d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_acoustic_vrz3d_backward_bs, in); }));
    m.def("das_mu2d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_das_mu2d_forward, in); }));
    m.def("das_mu2d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_das_mu2d_backward_bs, in); }));
    m.def("das_mu3d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_das_mu3d_forward, in); }));
    m.def("das_mu3d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_das_mu3d_backward_bs, in); }));
    m.def("elastic2d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_elastic2d_forward, in); }));
    m.def("elastic2d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_elastic2d_backward_bs, in); }));
    m.def("elastic3d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_elastic3d_forward, in); }));
    m.def("elastic3d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_elastic3d_backward_bs, in); }));
    m.def("elastic_tti_sg2d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_elastic_tti_sg2d_forward, in); }));
    m.def("elastic_tti_sg2d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_elastic_tti_sg2d_backward_bs, in); }));
    m.def("elastic_tti_sg3d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_elastic_tti_sg3d_forward, in); }));
    m.def("elastic_tti_sg3d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_elastic_tti_sg3d_backward_bs, in); }));
    m.def("elastic_vr2d_forward_runner", with_stream_forward([](const ForwardInput& in) -> ForwardRunnerPtr { return std::make_shared<ShimForwardRunner>(ID_elastic_vr2d_forward, in); }));
    m.def("elastic_vr2d_backward_bs_runner", with_stream_backward([](const BackwardInput& in) -> BackwardRunnerPtr { return std::make_shared<ShimBackwardRunner>(ID_elastic_vr2d_backward_bs, in); }));
}
